export const PARTY_MECHANICS = [
  { id: 'wall-air-dribble', name: 'Wall Air Dribble', difficulty: 'Easy' },
  { id: 'ground-to-air-dribble', name: 'Ground-to-Air Dribble', difficulty: 'Easy' },
  { id: 'ceiling-shot', name: 'Ceiling Shot', difficulty: 'Easy' },
  { id: 'double-tap', name: 'Double Tap', difficulty: 'Easy' },
  { id: 'backboard-read', name: 'Backboard Read', difficulty: 'Easy' },
  { id: 'forty-five-flick', name: '45° Flick', difficulty: 'Easy' },
  { id: 'musty-flick', name: 'Musty Flick', difficulty: 'Easy' },
  { id: 'flick-goal', name: 'Flick Goal', difficulty: 'Easy' },
  { id: 'half-flip-goal', name: 'Half Flip Goal', difficulty: 'Easy' },
  { id: 'wavedash-shot', name: 'Wavedash Shot', difficulty: 'Easy' },
  { id: 'long-goal-shot-from-wall', name: 'Long Goal Shot From Wall', difficulty: 'Easy' },
  { id: 'hook-shot-100-kph', name: 'Hook Shot — 100+ KPH', difficulty: 'Easy' },
  { id: 'half-field-dribble', name: 'Dribble From Half Field to Goal — Flicks Allowed', difficulty: 'Easy' },
  { id: 'crossbar-down-shot', name: 'Crossbar Down Shot', difficulty: 'Easy' },
  { id: 'turtle-goal', name: 'Turtle Goal', difficulty: 'Easy' },
  { id: 'sideflip-shot', name: 'Sideflip Shot', difficulty: 'Easy' },
  { id: 'fast-aerial-goal', name: 'Fast Aerial Goal', difficulty: 'Easy' },
  { id: 'under-5-kph-shot', name: 'Less Than 5 KPH Shot', difficulty: 'Easy' },
  { id: 'ninety-degree-flick', name: '90° Flick', difficulty: 'Easy' },
  { id: 'backwards-half-field-dribble', name: 'Backwards Dribble From Half Field to Goal — Flicks Allowed', difficulty: 'Easy' },
  { id: 'diagonal-flick', name: 'Diagonal Flick', difficulty: 'Easy' },
  { id: 'evan-pop', name: 'Evan Pop', difficulty: 'Easy' },
  { id: 'doomsee-dish', name: 'Doomsee Dish', difficulty: 'Easy' },
  { id: 'one-eighty-flick', name: '180 Flick', difficulty: 'Easy' },
  { id: 'top-corner', name: 'Top Corner', difficulty: 'Easy' },
  { id: 'breezi-flick', name: 'Breezi Flick', difficulty: 'Medium' },
  { id: 'kuxir-pinch', name: 'Kuxir Pinch', difficulty: 'Medium' },
  { id: 'ground-pinch-100', name: 'Ground Pinch 100+', difficulty: 'Medium' },
  { id: 'ceiling-pinch', name: 'Ceiling Pinch', difficulty: 'Medium' },
  { id: 'sidewall-redirect', name: 'Sidewall Redirect', difficulty: 'Medium' },
  { id: 'flip-reset', name: 'Flip Reset', difficulty: 'Medium' },
  { id: 'ground-to-flip-reset', name: 'Ground-to-Flip Reset', difficulty: 'Medium' },
  { id: 'wall-to-flip-reset', name: 'Wall-to-Flip Reset', difficulty: 'Medium' },
  { id: 'ceiling-to-flip-reset', name: 'Ceiling-to-Flip Reset', difficulty: 'Medium' },
  { id: 'cross-map-air-dribble', name: 'Cross Map Air Dribble', difficulty: 'Medium' },
  { id: 'pogo', name: 'Pogo', difficulty: 'Medium' },
  { id: 'ceiling-musty', name: 'Ceiling Musty', difficulty: 'Medium' },
  { id: 'ceiling-double-tap', name: 'Ceiling Double Tap', difficulty: 'Medium' },
  { id: 'air-dribble-double-tap', name: 'Air Dribble Double Tap', difficulty: 'Medium' },
  { id: 'glued-air-dribble', name: 'Glued Air Dribble', difficulty: 'Medium' },
  { id: 'mawkzy-flick', name: 'Mawkzy Flick', difficulty: 'Medium' },
  { id: 'plan-b', name: 'Plan B', difficulty: 'Medium' },
  { id: 'classy-flick', name: 'Classy Flick', difficulty: 'Medium' },
  { id: 'speed-flip-shot', name: 'Speed Flip Shot', difficulty: 'Medium' },
  { id: 'wall-dash-shot', name: 'Wall Dash Shot', difficulty: 'Medium' },
  { id: 'corner-read', name: 'Corner Read', difficulty: 'Medium' },
  { id: 'zap-dash-shot', name: 'Zap Dash Shot', difficulty: 'Medium' },
  { id: 'pop-reset', name: 'Pop Reset', difficulty: 'Medium' },
  { id: 'turtle-flick', name: 'Turtle Flick', difficulty: 'Medium' },
  { id: 'arsenal-reset', name: 'Arsenal Reset', difficulty: 'Medium' },
  { id: 'ground-pinch-120', name: 'Ground Pinch 120+', difficulty: 'Hard' },
  { id: 'cross-map-flip-reset', name: 'Cross Map Flip Reset', difficulty: 'Hard' },
  { id: 'double-flip-reset', name: 'Double Flip Reset', difficulty: 'Hard' },
  { id: 'triple-flip-reset', name: 'Triple Flip Reset', difficulty: 'Hard' },
  { id: 'stall-reset', name: 'Stall Reset', difficulty: 'Hard' },
  { id: 'heli-reset', name: 'Heli Reset', difficulty: 'Hard' },
  { id: 'pancake-reset', name: 'Pancake Reset', difficulty: 'Hard' },
  { id: 'pogo-double-tap', name: 'Pogo Double Tap', difficulty: 'Hard' },
  { id: 'reset-pogo', name: 'Reset Pogo', difficulty: 'Hard' },
  { id: 'kuxir-no-bounce', name: 'Kuxir No Bounce', difficulty: 'Hard' },
  { id: 'flip-reset-musty', name: 'Flip Reset Musty', difficulty: 'Hard' },
  { id: 'double-reset-musty', name: 'Double Reset Musty', difficulty: 'Hard' },
  { id: 'musty-double-tap', name: 'Musty Double Tap', difficulty: 'Hard' },
  { id: 'flip-reset-double-tap', name: 'Flip Reset Double Tap', difficulty: 'Hard' },
  { id: 'aztral-pinch', name: 'Aztral Pinch', difficulty: 'Hard' },
  { id: 'ceiling-pinch-no-bounce', name: 'Ceiling Pinch — No Bounce', difficulty: 'Hard' },
  { id: 'zen-shot', name: 'Zen Shot', difficulty: 'Hard' },
  { id: 'sting-pop', name: 'Sting Pop', difficulty: 'Hard' },
  { id: 'maktuf-reset', name: 'Maktuf Reset', difficulty: 'Hard' },
  { id: 'bbl-pinch', name: 'BBL Pinch', difficulty: 'Hard' },
  { id: 'double-pop-reset', name: 'Double Pop Reset', difficulty: 'Hard' },
  { id: 'ceiling-musty-double-tap', name: 'Ceiling Musty Double Tap', difficulty: 'Hard' },
  { id: 'double-musty', name: 'Double Musty', difficulty: 'Hard' },
  { id: 'rapid-reset', name: 'Rapid Reset', difficulty: 'Hard' },
  { id: 'turtle-air-dribble', name: 'Turtle Air Dribble', difficulty: 'Hard' },
  { id: 'psycho', name: 'Psycho', difficulty: 'Insane' },
]

export const PARTY_MECHANIC_BY_ID = Object.fromEntries(
  PARTY_MECHANICS.map((mechanic) => [mechanic.id, mechanic])
)

export function getPartyMechanic(mechanicId) {
  return PARTY_MECHANIC_BY_ID[mechanicId] || null
}

export function pickPartyMechanic() {
  return PARTY_MECHANICS[Math.floor(Math.random() * PARTY_MECHANICS.length)]
}
