import {BOOSTSTONE_RUINS} from './booststoneRuins'
import {useState} from 'react'
import {PARTY_CARS,formatPartyDieFace} from './partyCars'
import {getEnabledPartyCards,getPartyCardShopPrice} from './partyCards'
import {adjustPartyPlayerDev,preparePartyVisualDevTest,preparePartyLuckDevTest,preparePartyCardDevTest,preparePartyEventDevTest,configurePartyChestDev,configurePartyShopDev,preparePartyServiceDevTest,savePartyDevCheckpoint,restorePartyDevCheckpoint,recoverPartyPresentation,PARTY_LUCKY_OUTCOMES,PARTY_BAD_LUCK_OUTCOMES,PARTY_VERY_BAD_LUCK_OUTCOMES} from './partyMultiplayer'
const SCENARIOS=[['position','Any board position / path / junction'],['dice','Normal / special dice — any car and face'],['precision','Golden Precision Dice'],['gain','Gain Tokens'],['loss','Lose Tokens / floor at zero'],['trophy-loss','Lose a Trophy'],['gift-tokens','Hidden Gift → Tokens'],['gift-trophy','Hidden Gift → Trophy'],['mechanic','Blue Mechanic — any difficulty'],['danger','Red Danger — any difficulty'],['trophy-offer','Trophy purchase / decline'],['gate-choice','Garage junction / toll / stop'],['showcase','Showcase camera and rules'],['turn-order','Turn-order numbers 1–10 / review'],['bonus-tie','Bonus Trophy — everyone tied']]
export default function PartyBoardDev({room,roomCode,clientId,runAction,busy,actionBusy}){
 const [scenario,setScenario]=useState('dice'),[carId,setCarId]=useState(''),[face,setFace]=useState(-1),[balance,setBalance]=useState(20),[amount,setAmount]=useState(6),[difficulty,setDifficulty]=useState('Easy'),[finalStretch,setFinal]=useState(false),[category,setCategory]=useState(0),[luckType,setLuck]=useState('Lucky'),[outcome,setOutcome]=useState(''),[cardId,setCard]=useState('boost-canister'),[chest,setChest]=useState('crate-3-tokens'),[nodeId,setNode]=useState('n01'),[moves,setMoves]=useState(1),[fullHand,setFullHand]=useState(false)
 const [targetId,setTarget]=useState(clientId),[editKind,setEditKind]=useState('tokens'),[editAmount,setEditAmount]=useState(10)
 const car=PARTY_CARS.find(c=>c.id===carId),faces=car?.specialDie||[1,2,3,4,5,6]
 const pool=luckType==='Lucky'?PARTY_LUCKY_OUTCOMES:luckType==='Bad Luck'?PARTY_BAD_LUCK_OUTCOMES:PARTY_VERY_BAD_LUCK_OUTCOMES
 const act=fn=>runAction(async()=>{await savePartyDevCheckpoint(roomCode,clientId);await fn()})
 return <div className="party-dev-controls"><p><strong>Installed update: Party Fix 10-09-D</strong></p><p>Use a test room. These controls change the room for everyone. Save a checkpoint before testing; Restore returns the board state and balances.</p>
 <div className="menu"><button disabled={busy||Boolean(room.devBoardCheckpoint)} onClick={()=>runAction(()=>savePartyDevCheckpoint(roomCode,clientId))}>Save test checkpoint</button><button disabled={!room.devBoardCheckpoint} onClick={()=>runAction(()=>restorePartyDevCheckpoint(roomCode,clientId),true)}>Restore checkpoint</button><button onClick={()=>runAction(()=>recoverPartyPresentation(roomCode,clientId),true)}>Skip animation / close dice</button></div>
 <fieldset className="party-dev-player-editor"><legend>Edit any player</legend><label>Player<select value={targetId} onChange={e=>setTarget(e.target.value)}>{Object.values(room.players||{}).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Resource<select value={editKind} onChange={e=>setEditKind(e.target.value)}><option value="tokens">Tokens</option><option value="trophies">Trophies</option><option value="cards">Action Cards</option></select></label>{editKind==='cards'?<label>Card<select value={cardId} onChange={e=>setCard(e.target.value)}>{getEnabledPartyCards().map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>:<label>Amount<input type="number" min="1" max="9999" step="1" value={editAmount} onChange={e=>setEditAmount(Number(e.target.value))}/></label>}<div className="menu">{[1,-1].map(sign=><button key={sign} disabled={actionBusy||!Number.isInteger(editAmount)||editAmount<1} onClick={()=>runAction(()=>adjustPartyPlayerDev(roomCode,clientId,targetId,editKind==='cards'?(sign>0?'add-card':'remove-card'):editKind,sign*editAmount,cardId),true)}>{sign>0?'Add':'Subtract'} {editKind==='cards'?'one Card':editKind}</button>)}</div><small>Balances stop at zero. Cards keep the three-card limit. Manual changes do not alter bonus statistics.</small></fieldset>
 <div className="menu"><button disabled={busy} onClick={()=>act(()=>preparePartyVisualDevTest(roomCode,clientId,'gift-tokens',{finalStretch}))}>Test Hidden Gift — Tokens</button><button disabled={busy} onClick={()=>act(()=>preparePartyVisualDevTest(roomCode,clientId,'gift-trophy'))}>Test Hidden Gift — Trophy</button></div>
 <label>Action Card<select value={cardId} onChange={e=>setCard(e.target.value)}>{getEnabledPartyCards().map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button disabled={busy} onClick={()=>act(()=>preparePartyCardDevTest(roomCode,clientId,cardId))}>Prepare Card</button>
 <label>Board / animation test<select value={scenario} onChange={e=>setScenario(e.target.value)}>{SCENARIOS.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>
 {scenario==='position'&&<><label>Start node<select value={nodeId} onChange={e=>setNode(e.target.value)}>{BOOSTSTONE_RUINS.nodes.map(n=><option key={n.id} value={n.id}>{n.id} — {n.type}</option>)}</select></label><label>Movement points<input type="number" min="1" max="20" value={moves} onChange={e=>setMoves(Number(e.target.value))}/></label></>}
 {scenario==='dice'&&<><label>Die<select value={carId} onChange={e=>setCarId(e.target.value)}><option value="">Normal 1–6</option>{PARTY_CARS.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Stop result<select value={face} onChange={e=>setFace(Number(e.target.value))}><option value={-1}>Random</option>{faces.map((f,i)=><option key={i} value={i}>Face {i+1}: {formatPartyDieFace(f)}</option>)}</select></label></>}
 {['gain','loss','trophy-offer','gate-choice','danger','dice'].includes(scenario)&&<label>Starting Tokens<input type="number" min="0" max="999" value={balance} onChange={e=>setBalance(Number(e.target.value))}/></label>}
 {['gain','loss'].includes(scenario)&&<label>Amount<input type="number" min="1" max="100" value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label>}
 {['mechanic','danger'].includes(scenario)&&<label>Difficulty<select value={difficulty} onChange={e=>setDifficulty(e.target.value)}>{['Easy','Medium','Hard','Insane'].map(d=><option key={d}>{d}</option>)}</select></label>}
 {['mechanic','danger','gift-tokens'].includes(scenario)&&<label><input type="checkbox" checked={finalStretch} onChange={e=>setFinal(e.target.checked)}/> Final three rounds</label>}
 {scenario==='bonus-tie'&&<label>Category<select value={category} onChange={e=>setCategory(Number(e.target.value))}>{['Minigame','Rich','Eventful','Item','Sightseer','Slowpoke','Unlucky'].map((v,i)=><option key={v} value={i}>{v}</option>)}</select></label>}
 <button disabled={busy} onClick={()=>act(()=>preparePartyVisualDevTest(roomCode,clientId,scenario,{carId,faceIndex:face,balance,amount,difficulty,finalStretch,category,nodeId,moves}))}>Prepare selected test</button>
 <label>Luck roulette<select value={luckType} onChange={e=>{setLuck(e.target.value);setOutcome('')}}>{['Lucky','Bad Luck','Very Bad Luck'].map(t=><option key={t}>{t}</option>)}</select></label><label>Outcome<select value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="">Random</option>{pool.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><button disabled={busy} onClick={()=>act(()=>preparePartyLuckDevTest(roomCode,clientId,luckType,outcome))}>Test roulette outcome</button>
 <label>Chest reward<select value={chest} onChange={e=>setChest(e.target.value)}>{[['crate-3-tokens','3 Tokens'],['crate-5-tokens','5 Tokens'],['crate-precision-dice','Precision Dice'],['crate-golden-teleporter','Golden Teleporter'],['crate-shield','Shield']].map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></label><button disabled={busy} onClick={()=>act(async()=>{await preparePartyEventDevTest(roomCode,clientId,'supply-crates');await configurePartyChestDev(roomCode,clientId,chest)})}>Test chest reward (choose any chest)</button>
 <label>Shop Card<select value={cardId} onChange={e=>setCard(e.target.value)}>{getEnabledPartyCards().filter(c=>getPartyCardShopPrice(c.id)!==null).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label><input type="checkbox" checked={fullHand} onChange={e=>setFullHand(e.target.checked)}/> Full hand (test inventory limit)</label><button disabled={busy} onClick={()=>act(async()=>{await preparePartyServiceDevTest(roomCode,clientId,'Shop');await configurePartyShopDev(roomCode,clientId,cardId,fullHand)})}>Test selected shop Card</button>
 </div>
}
