import { PARTY_MECHANICS } from './partyMechanics'
import { TARGETS, WORDS, REQUIREMENTS, groupsBy, numeric, shuffle, sideOf, finishSprintScores } from './partyChallengeEngine'
const need=(c,m='This secret action is unavailable.')=>{if(!c)throw Error(m)}
const nOf=g=>parseInt(g.challengeId.split('-')[1]);const pick=(a,r)=>a[Math.floor(r()*a.length)]
export const SECRET_ENGINES=['target','auction','guess','luck','imposter','boss','potato']
const result=(g,groups,now)=>{g.result={placements:groups,revealAt:now+650};g.phase='result'}
const win=(g,s,now)=>result(g,s===-1?[g.ids]:[g.sides[s],g.sides[1-s]],now)
export function secretParticipants(g){const n=nOf(g);if(g.engine==='auction'||g.engine==='luck'||g.engine==='imposter')return g.ids;
 if(g.engine==='target')return [g.sides[(g.turn+1)%2][0]];
 if(g.engine!=='guess')return [];
 const shooter=g.shooters?.[g.shot];if(g.sprint&&g.format==='1v1')return g.ids.filter(id=>id!==shooter);if(g.sprint&&['1v1v1','1v1v1v1'].includes(g.format))return g.tieGroups?.flat()||g.ids;if(g.format==='1v2'||g.format==='1v3')return [g.captain];if(g.format==='2v2'){const opponents=g.sides[1-sideOf(g,shooter)];return n===39?[opponents[0]]:opponents}return n===39?g.ids.filter(id=>id!==shooter):g.ids}
export function makeSecretDeal(g,r,hostId){const n=nOf(g),deals={};if(g.engine==='imposter'){const imp=pick(g.ids,r);let prompt;if(n===81)prompt=pick(WORDS,r);else{const type=pick(['mechanic','speed','requirement'],r);if(type==='mechanic'){const m=pick(PARTY_MECHANICS,r);prompt={id:m.id,name:m.name,type}}else if(type==='speed'){const v=pick([70,80,90,100,110,120,130,140],r);prompt={id:String(v),name:v+' KPH',type}}else {const v=pick(REQUIREMENTS,r);prompt={id:v,name:v,type}}}for(const id of g.ids)deals[id]=id===imp?{role:'imposter'}:{role:'normal',prompt};}
 else if(g.engine==='target'){const target=pick(TARGETS,r);for(const id of g.sides[g.turn%2])deals[id]={target}}
 else if(g.engine==='boss'){const options=shuffle(PARTY_MECHANICS,r).slice(0,3).map(m=>({id:m.id,name:m.name,difficulty:m.difficulty}));deals[g.sides[0][0]]={options}}
 else if(g.engine==='luck')for(const id of g.ids)deals[id]={first:1+Math.floor(r()*10),second:1+Math.floor(r()*10)};
 else if(g.engine==='potato')deals[hostId]={duration:10000+r()*50000};return deals}
function clearRound(g){g.commits={};g.reveals={};g.sealed={};g.secretRound=(g.secretRound||0)+1}
export function secretAction(g,a,uid,host,r,now){need(g.phase==='active'||g.phase==='result');const n=nOf(g);const admin=()=>need(host,'Only the Battle Host can do this.');const own=id=>need(uid===id,'Only that player can submit this input.');const p=secretParticipants(g);
 if(a.type==='deal'){admin();need(!Object.keys(g.sealed||{}).length);g.sealed=a.packets;g.dealId=a.dealId;return}
 if(a.type==='commit'){need(p.includes(uid));need(!g.commits?.[uid],'Your input is locked.');if(g.engine==='guess'&&n===39)need(g.estimate!==undefined,'Wait for the shooter estimate.');if(g.engine==='imposter')need(g.subphase==='vote');if(g.engine==='target')need(g.subphase==='predict');g.commits||={};g.commits[uid]=a.commit;return}
 if(a.type==='reveal'){need(p.every(id=>g.commits?.[id]),'Wait for everyone to lock an input.');need(p.includes(uid)&&!Object.hasOwn(g.reveals||{},uid));g.reveals||={};if(g.engine==='auction')need(Number.isInteger(a.value)&&a.value>=1&&a.value<=5);if(g.engine==='luck')need(Number.isInteger(a.value)&&a.value>=1&&a.value<=10);if(g.engine==='target')need(TARGETS.includes(a.value));if(g.engine==='guess')n===39?need(['higher','lower'].includes(a.value)):numeric(a.value);g.reveals[uid]=a.value;
 if(p.every(id=>Object.hasOwn(g.reveals,id))){if(g.engine==='auction'){g.bidOrder=shuffle(p,r).sort((a,b)=>g.reveals[a]-g.reveals[b]);g.bidIndex=0;g.subphase='attempt'}else if(g.engine==='imposter')resolveVotes(g,r);else if(g.engine==='target')g.subphase='revealTarget';else if(g.engine==='guess')g.subphase='actual'}return}
 if(g.engine==='luck'){if(a.type==='luckReveal'){admin();need(p.every(id=>Object.hasOwn(g.reveals||{},id)));settle(g,g.reveals,now,false,'max');return}}
 if(g.engine==='guess'){if(a.type==='estimate'){own(g.shooters[g.shot]);need(n===39&&g.estimate===undefined);g.estimate=numeric(a.value);return}if(a.type==='actual'){own(g.shooters[g.shot]);need(g.subphase==='actual'||g.subphase==='shotResult');if(g.subphase==='shotResult'){for(const id of p){const v=g.reveals[id];g.scores[id]-=(n===39?(g.actual===g.estimate?0:(v==='higher')===(g.actual>g.estimate)?1:0):Math.abs(numeric(v)-g.actual))}}const value=numeric(a.value);g.actual=value;for(const id of p){const v=g.reveals[id];g.scores[id]+=(n===39?(value===g.estimate?0:(v==='higher')===(value>g.estimate)?1:0):Math.abs(numeric(v)-value))}g.subphase='shotResult';return}
 if(a.type==='nextShot'){admin();need(g.subphase==='shotResult');g.shot++;if(g.shot===g.shooters.length){if(g.sprint){finishSprintScores(g,g.scores,now,true);if(g.phase==='tiebreak'){g.round++;g.phase='active';g.shot=0;g.scores=Object.fromEntries(g.ids.map(id=>[id,0]));if(g.format.includes('1v1v1'))g.shooters=[pick(g.ids,r)];clearRound(g);delete g.actual;g.subphase='guess'}return}if(g.format==='1v2'||g.format==='1v3'){win(g,g.scores[g.captain]<=(g.format==='1v2'?25:20)?1:0,now);return}settle(g,g.scores,now,n===30,'sum');if(n===30&&g.result.placements.length===1&&g.format!=='1v1v1'&&g.format!=='1v1v1v1'){delete g.result;g.phase='active';g.shot=0;g.scores=Object.fromEntries(g.ids.map(id=>[id,0]))}else return}clearRound(g);delete g.estimate;delete g.actual;g.subphase='guess';return}}
 if(g.engine==='target'){if(a.type==='attackResult'){need(g.sides[g.turn%2].includes(uid));need(g.subphase==='attack');g.attackScore=numeric(a.value,true);need(g.attackScore<=2);g.subphase='predict';return}if(a.type==='targetReveal'){need(g.sides[g.turn%2].includes(uid)&&g.subphase==='revealTarget');need(TARGETS.includes(a.target));g.target=a.target;g.scores[g.sides[g.turn%2][0]]+=g.attackScore;const defender=g.sides[(g.turn+1)%2][0];if(g.reveals[defender]===a.target)g.scores[defender]++;g.subphase='shotResult';return}if(a.type==='nextShot'){admin();need(g.subphase==='shotResult');g.shot++;if(g.shot<6)g.turn=g.shot<3?0:1;else g.turn=(g.shot-6)%2;
 if(g.shot===6||g.shot>6&&(g.shot-6)%2===0){const x=g.scores[g.sides[0][0]],y=g.scores[g.sides[1][0]];if(x!==y){win(g,x>y?0:1,now);return}}clearRound(g);g.subphase='attack';return}}
 if(g.engine==='auction'){if(a.type==='rerollHard'){admin();need(!Object.keys(g.commits||{}).length&&g.subphase==='bid');g.mechanic=pick(PARTY_MECHANICS.filter(m=>m.difficulty==='Hard'),r);return}if(a.type==='auctionAttempt'){const id=g.bidOrder[g.bidIndex];own(id);need(g.subphase==='attempt');if(a.made){g.scores[id]++;g.subphase='roundResult'}else if(++g.bidIndex>=g.bidOrder.length)g.subphase='roundResult';return}if(a.type==='nextRound'){admin();need(g.subphase==='roundResult');if(g.round===3){settle(g,g.scores,now);return}g.round++;clearRound(g);g.mechanic=pick(PARTY_MECHANICS.filter(m=>m.difficulty==='Hard'),r);g.subphase='bid';return}}
 if(g.engine==='imposter'){if(a.type==='rolesReady'){admin();need(g.subphase==='roles'&&Object.keys(g.sealed||{}).length===g.ids.length);g.subphase='freeClues';g.turn=0;return}if(a.type==='startDiscussion'){admin();need(g.subphase==='freeClues');g.subphase='discussion';g.timer={startedAt:now,duration:120000,pauseTotal:0};return}if(a.type==='voteStart'||a.type==='tick'){if(a.type==='voteStart')admin();need(g.subphase==='discussion');if(a.type==='tick')need(g.timer&&!g.timer.pausedAt&&now>=g.timer.startedAt+g.timer.duration+(g.timer.pauseTotal||0),'Discussion is still active.');g.commits={};g.reveals={};delete g.timer;g.subphase='vote';return}
 if(a.type==='accusedRole'){need(uid===g.accused&&g.subphase==='accused');if(a.imposter){g.imposter=uid;g.subphase='finalGuess'}else{g.subphase='identify';g.wrongAccused=uid}return}
 if(a.type==='identify'){need(g.subphase==='identify'&&a.imposter);g.imposter=uid;result(g,[[uid],g.ids.filter(id=>id!==uid)],now);return}
 if(a.type==='finalGuess'){need(g.subphase==='finalGuess'&&uid===g.imposter&&!g.guess);need(typeof a.value==='string'&&a.value.length<300);g.guess=a.value;g.subphase='verify';return}
 if(a.type==='verify'){need(g.subphase==='verify'&&uid!==g.imposter);g.prompt=a.prompt;result(g,g.guess===a.prompt.id?[[g.imposter],g.ids.filter(id=>id!==g.imposter)]:[g.ids.filter(id=>id!==g.imposter),[g.imposter]],now);return}}
 if(g.engine==='boss'){const boss=g.sides[0][0];if(a.type==='bossChoose'){need(uid===boss&&g.subphase==='bossChoose');const m=PARTY_MECHANICS.find(m=>m.id===a.value);need(m);g.mechanic={id:m.id,name:m.name,difficulty:m.difficulty};g.subphase='challenger';return}if(a.type==='challenger'){need(g.sides[1].includes(uid)||host);const alive=g.sides[1].filter(id=>!g.out.includes(id));need(g.subphase==='challenger'&&alive.includes(a.playerId)&&(alive.length===1||a.playerId!==g.lastChallenger));g.challenger=a.playerId;g.attempt=1;g.subphase='attempt';return}if(a.type==='bossAttempt'){own(g.challenger);need(g.subphase==='attempt');if(a.made)g.subphase='roundResult';else if(g.attempt++===2){g.out.push(g.challenger);g.subphase='roundResult'}if(g.sides[1].every(id=>g.out.includes(id)))win(g,0,now);return}if(a.type==='nextRound'){admin();need(g.subphase==='roundResult');if(g.round===g.totalRounds){win(g,1,now);return}g.lastChallenger=g.challenger;g.round++;clearRound(g);g.subphase='bossChoose';return}}
 if(g.engine==='potato'){if(a.type==='bombStart'){admin();need(Object.keys(g.sealed||{}).length&&!g.hiddenStartedAt);g.hiddenStartedAt=now+1500;g.exploded=false;return}if(a.type==='explode'){admin();need(g.hiddenStartedAt&&!g.exploded);g.exploded=true;return}if(a.type==='potatoResult'){admin();need(g.exploded&&[0,1].includes(a.side));win(g,a.side,now);return}if(a.type==='retryPotato'){admin();clearRound(g);delete g.hiddenStartedAt;g.exploded=false;return}}
 throw Error('Invalid secret Challenge action.')
}
function settle(g,values,now,lower=false,mode='sum'){if(g.format==='1v1v1'||g.format==='1v1v1v1'){result(g,groupsBy(g.ids,values,lower),now);return}const scores=g.sides.map(ids=>mode==='max'?Math.max(...ids.map(id=>values[id]||0)):ids.reduce((s,id)=>s+(values[id]||0),0));win(g,scores[0]===scores[1]?-1:(scores[0]>scores[1])!==lower?0:1,now)}
function resolveVotes(g,r){const counts=Object.fromEntries(g.ids.map(id=>[id,0]));for(const [id,vote] of Object.entries(g.reveals)){need(g.ids.includes(vote)&&vote!==id,'Invalid vote.');counts[vote]++}g.voteCounts=counts;const max=Math.max(...Object.values(counts)),top=g.ids.filter(id=>counts[id]===max);if(top.length>1){g.subphase='freeClues';g.round++;g.order=shuffle(g.ids,r);g.turn=0;delete g.timer}else{g.accused=top[0];g.subphase='accused';delete g.timer}}
