import { useEffect, useRef, useState } from 'react'
import { CHALLENGE_BY_ID, PARTY_CHALLENGES, FORMAT_SIZES } from './partyChallengeCatalog'
import { timerElapsed, timerLeft, bombPosition, lightAt, sideOf, TARGETS, WORDS, REQUIREMENTS, CAR_NAMES, PEOPLE, CHALLENGE_REWARDS, rewardDistribution } from './partyChallengeEngine'
import { SECRET_ENGINES, secretParticipants } from './partyChallengeSecretEngine'
import { unseal, commitment } from './partyChallengeSecrets'
import { registerBattleKey, sendChallengeAction, confirmChallengeRewards, cancelChallenge, startRoundChallenge, launchChallengeDevTest, challengeNow } from './partyChallengeTransport'
import { PARTY_MECHANICS } from './partyMechanics'
import './partyChallenge.css'
let audioContext, audioEnabled=false
export async function battleSound(word='Ready'){audioEnabled=true;const Audio=window.AudioContext||window.webkitAudioContext;if(Audio){audioContext||=new Audio();await audioContext.resume();const o=audioContext.createOscillator(),gain=audioContext.createGain();o.connect(gain);gain.connect(audioContext.destination);o.frequency.value=word==='Explosion'?70:word==='red'?220:word==='yellow'?440:660;gain.gain.setValueAtTime(.12,audioContext.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.3);o.start();o.stop(audioContext.currentTime+.32)}if('speechSynthesis'in window&&word!=='Tick'){speechSynthesis.speak(new SpeechSynthesisUtterance(word))}}
export function BattleAudioCheck(){const [status,setStatus]=useState('');return <div className="bc-audio"><button type="button" onClick={()=>battleSound('Audio ready').then(()=>setStatus('If you heard the tone and voice, audio is ready.')).catch(()=>setStatus('Audio blocked. Check your browser sound settings.'))}>Test Battle Audio</button><small>{status||'Each player: click once to enable Battle sounds.'}</small></div>}
const yes=text=>window.confirm(text)
function useNow(enabled=true){const [now,setNow]=useState(challengeNow());useEffect(()=>{if(!enabled)return;setNow(challengeNow());const t=setInterval(()=>setNow(challengeNow()),100);return()=>clearInterval(t)},[enabled]);return enabled?now:challengeNow()}
const fmt=n=>(Math.max(0,n)/1000).toFixed(1)+'s'
function Num({label='Value',onSubmit,integer=false,disabled=false}){const [v,setV]=useState('');return <form className="bc-inline" onSubmit={e=>{e.preventDefault();if(v!==''&&Number.isFinite(Number(v))&&Number(v)>=0&&(!integer||Number.isInteger(Number(v)))){onSubmit(Number(v));setV('')}}}><label>{label}<input required type="number" min="0" step={integer?'1':'any'} value={v} disabled={disabled} onChange={e=>setV(e.target.value)}/></label><button disabled={disabled||v===''}>Submit</button></form>}
function Placement({g,names,onSubmit,allowDraw=false,override=false}){const [ranks,setRanks]=useState({});const team=g.sides.length===2&&!['1v1v1','1v1v1v1'].includes(g.format);return <div className="bc-controls">{team?g.sides.map((s,i)=><button key={i} onClick={()=>onSubmit([s,g.sides[1-i]],override)}>{s.map(names).join(' + ')} Won</button>):<><p>Enter placements. Use equal ranks only when this Challenge permits ties.</p>{g.ids.map(id=><label key={id}>{names(id)}<select value={ranks[id]||''} onChange={e=>setRanks({...ranks,[id]:Number(e.target.value)})}><option value="">Place…</option>{g.ids.map((_,i)=><option key={i} value={i+1}>{i+1}</option>)}</select></label>)}<button disabled={!g.ids.every(id=>ranks[id])} onClick={()=>{const groups=Object.values(g.ids.reduce((o,id)=>{(o[ranks[id]]||=[]).push(id);return o},{}));onSubmit(groups,override)}}>Submit placements</button></>}{allowDraw&&<button onClick={()=>onSubmit([g.ids],override)}>Draw</button>}</div>}
export function ChallengeDev({room,roomCode,clientId,runAction,busy=false}){const [id,setId]=useState(PARTY_CHALLENGES[0].id),[format,setFormat]=useState('1v1');const c=CHALLENGE_BY_ID[id],count=Object.keys(room.players||{}).length;return <section className="bc-dev"><h3>Challenge Test Lab</h3><label>Challenge<select value={id} onChange={e=>{setId(e.target.value);setFormat(CHALLENGE_BY_ID[e.target.value].formats[0])}}>{PARTY_CHALLENGES.map(c=><option value={c.id} key={c.id}>{c.number}. {c.name}</option>)}</select></label><label>Format<select value={format} onChange={e=>setFormat(e.target.value)}>{c.formats.map(f=><option key={f} value={f} disabled={FORMAT_SIZES[f]>count}>{f}{FORMAT_SIZES[f]>count?' — needs '+FORMAT_SIZES[f]+' players':''}</option>)}</select></label><button disabled={busy||FORMAT_SIZES[format]>count} onClick={()=>yes('Launch this test Battle? This replaces the current test turn. Rewards affect this room.')&&runAction(()=>launchChallengeDevTest(roomCode,clientId,id,format))}>Launch selected Battle</button></section>}
export default function PartyChallenge({room,roomCode,clientId,onNextRound}){const b=room.phase==='round-complete'?room.roundBattle:room.turnState?.battle;const [busy,setBusy]=useState(false),[error,setError]=useState('');const isHost=b?b.hostId===clientId:room.hostId===clientId;const names=id=>room.players?.[id]?.name||'Departed player';
 useEffect(()=>{registerBattleKey(roomCode,clientId).catch(e=>setError(e.message))},[roomCode,clientId]);
 async function run(fn){if(busy)return;setBusy(true);setError('');try{await fn()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const act=a=>run(()=>sendChallengeAction(roomCode,clientId,b.id,a));const missing=b?.participantIds?.some(id=>!room.players?.[id]||room.departedPlayers?.[id]);
 if(!b)return <section className="bc"><h2>Round {room.currentRound} Challenge</h2><p>Everyone participates. The format, Challenge, and teams are selected in that order.</p>{isHost?<button disabled={busy} onClick={()=>run(()=>startRoundChallenge(roomCode,clientId))}>Select round Challenge</button>:<p>Waiting for the host…</p>}{error&&<p role="alert">{error}</p>}</section>;
 if(b.status==='resolved')return <section className="bc"><h2>{b.name}</h2><p>{b.resultMessage}</p>{b.rewards&&Object.entries(b.rewards).map(([id,n])=><p key={id}>{names(id)}: +{n} Tokens</p>)}{room.phase==='round-complete'&&isHost&&<button onClick={onNextRound}>Continue {room.currentRound>=room.settings.rounds?'to final standings':'to next round'}</button>}</section>;
 return <section className="bc" aria-label="Party Challenge"><p className="bc-eyebrow">{b.source==='round-end'?'Round Challenge':b.source==='challenge-glove'?'Challenge Glove':'Battle'} · Host: {names(b.hostId)}</p>
 <h2>{b.name}</h2>{error&&<p role="alert" className="bc-error">{error} <button disabled={busy} onClick={()=>run(()=>registerBattleKey(roomCode,clientId))}>Retry connection</button></p>}{missing&&<p>A participant left. The host can cancel below and start a new Battle.</p>}
 {b.stage==='format'&&<><p>Choose the battle format. The game and teams will be random.</p>{Object.entries(FORMAT_SIZES).map(([f,n])=><button disabled={!isHost||busy||n>b.participantIds.length} key={f} onClick={()=>act({type:'format',format:f})}>{f}</button>)}</>}
 {['formatReveal','draw','challengeReveal'].includes(b.stage)&&<><h3>{b.format}</h3><p>{b.stage==='formatReveal'?'Format selected':b.stage==='draw'?'Ready to draw a Challenge':'Challenge selected. Next: random teams.'}</p>{isHost&&<button disabled={busy} onClick={()=>act({type:'next'})}>{b.stage==='draw'?'Draw Challenge':'Continue'}</button>}</>}
 {b.stage==='rules'&&<><Teams g={b.game} names={names}/><Rules g={b.game}/><BattleAudioCheck/>{isHost&&['mode','arena'].includes(b.game.engine)&&<button onClick={()=>act({type:'game',action:{type:'reroll',confirmed:true}})}>Agreed setting reroll</button>}{[23,40,49,50].includes(parseInt(b.game.challengeId.split('-')[1]))&&['green','yellow','red','Tick','Explosion'].map(sound=><button key={sound} onClick={()=>battleSound(sound)}>Test {sound}</button>)}{isHost?<button disabled={busy} onClick={()=>act({type:'next'})}>Everyone ready — Continue</button>:<p>Read the rules. Waiting for the Battle Host.</p>}</>}
 {b.stage==='play'&&<ChallengeGame g={b.game} uid={clientId} host={isHost} hostId={b.hostId} names={names} keys={room.battleKeys||{}} busy={busy} action={a=>act({type:'game',action:a})} root/>}
 {b.game?.result&&b.stage==='play'&&<Rewards b={b} names={names} host={isHost} busy={busy} confirm={()=>run(()=>confirmChallengeRewards(roomCode,clientId,b.id))}/>}
 {(isHost||room.hostId===clientId)&&<details className="bc-recovery"><summary>Host recovery</summary><p>Cancel for a disconnect or technical problem. No rewards are applied.</p><button disabled={busy} onClick={()=>yes('Cancel this Battle with no reward?')&&run(()=>cancelChallenge(roomCode,clientId,b.id))}>Cancel Battle</button></details>}
 </section>
}
function Teams({g,names}){const hidden=g.engine==='imposter';return <div className="bc-teams">{(hidden?[g.ids]:g.displayTeams||g.sides).map((s,i)=><div key={i}><strong>{hidden?'Players':s.length>1?'Team '+(i+1):'Player'}</strong><p>{s.map(names).join(' + ')}</p></div>)}</div>}
const SPRINT_RULES={'Speed Sprint':'One shot each. Successful goal KPH counts; a miss is 0. Higher wins.','Pinch Sprint':'One legitimate pinch attempt each. Successful goal KPH counts; a miss is 0. Higher wins.','Crossbar Sprint':'Two attempts each. A crossbar hit is 1 point; a miss is 0. Tied players get one extra attempt each.','Freestyle Sprint':'Two attempts each. Judge the best successful shot by difficulty, creativity, execution, and cleanliness. If tied, take one extra attempt each; if everyone misses, repeat.','KPH Guess Sprint':'Head-to-head: take one shot each and guess only the opponent’s shot. FFA: one randomly assigned shared shot; everyone guesses, including the shooter. Lock guesses before revealing goal speed. Lowest error wins.'};
const SPRINT_TEAM_RULES={'Speed Sprint':'Add both teammates’ KPH.','Pinch Sprint':'One team pinch per duo; both players must be involved.','Crossbar Sprint':'Add both teammates’ hits.','Freestyle Sprint':'Two TEAM-PLAY attempts per team; both teammates must be meaningfully involved.','KPH Guess Sprint':'One shooter per team; both opponents guess that shot. Compare combined team error.'};
function Rules({g}){const c=CHALLENGE_BY_ID[g.challengeId];return <details className="bc-rules" open><summary>{g.sprint||c.name} · {g.format} — Rules and setup</summary>{g.sprint?<p>{SPRINT_RULES[g.sprint]} {g.format==='2v2'?SPRINT_TEAM_RULES[g.sprint]:''} Resolve ties before confirming the event. Only tied FFA players repeat; settled placements stay fixed.</p>:null}{g.playerChosen&&<p>Choose/randomize your Rocket League mode yourselves. Resolve the match to one winner.</p>}{!g.sprint&&!g.playerChosen&&<pre>{c.rules}</pre>}</details>}
function Rewards({b,names,host,busy,confirm}){const now=useNow();if(now<b.game.result.revealAt)return <p>Calculating result…</p>;let rank=1;const rewards=rewardDistribution(b);return <div className="bc-results"><h3>Battle results & Token distribution</h3>{b.game.result.placements.map((ids,i)=>{const place=rank;rank+=ids.length;return <p key={i}>#{place} {ids.map(names).join(' / ')} — {ids.map(id=>'+'+rewards[id]+' Tokens').join(' / ')}</p>})}<p>Rewards apply once when the Battle Host continues.</p>{host&&<button disabled={busy} onClick={confirm}>Confirm rewards & Continue</button>}</div>}
export function ChallengeGame({g,uid,host,hostId,names,keys,busy,action,root=false}){const now=useNow(Boolean(g.timer||g.hiddenStartedAt||g.result)),[correction,setCorrection]=useState(false),[privateValue,setPrivate]=useState(null),[unlock,setUnlock]=useState(false);const lastSound=useRef('');const [privateError,setPrivateError]=useState('');const packet=g.sealed?.[uid];const n=parseInt(g.challengeId.split('-')[1]),mine=id=>host||id===uid,alive=g.order.filter(id=>!g.out?.includes(id)),current=alive[g.turn%Math.max(1,alive.length)],inMatch=g.ids.includes(uid);
 useEffect(()=>{let active=true;setPrivate(null);setPrivateError('');if(packet)unseal(uid,packet).then(v=>active&&setPrivate(v)).catch(()=>active&&setPrivateError('Private information could not be opened. Use the original browser, or ask the host to restart this Challenge.'));return()=>{active=false}},[packet?.body,uid]);
 // Reveal only after every required participant committed. Ciphertexts stay unreadable until then.
 const p=SECRET_ENGINES.includes(g.engine)?secretParticipants(g):[];const commit=g.commits?.[uid];const allLocked=p.length>0&&p.every(id=>g.commits?.[id]);
 useEffect(()=>{let cancelled=false;if(commit&&allLocked&&!Object.hasOwn(g.reveals||{},uid)&&!busy)unseal(uid,commit.packet).then(v=>{if(!cancelled)action({type:'reveal',value:v.value,salt:v.salt})}).catch(()=>setPrivateError('Your locked answer could not be opened. Use the original browser, or ask the host to restart.'));return()=>{cancelled=true}},[commit?.hash,allLocked,g.reveals?.[uid],busy]);
 useEffect(()=>{if(!host||busy||g.result||g.phase!=='active')return;const timed=['names','reverseSpeed','gauntlet','timedGoals','hunt'].includes(g.engine)&&g.timer&&!g.timer.pausedAt&&timerLeft(g.timer,now)===0;const bomb=g.engine==='bomb'&&Math.abs(bombPosition(g,now))>=1;if(timed||bomb)action({type:'tick'});if(g.engine==='potato'&&g.hiddenStartedAt&&!g.exploded&&privateValue&&now>=g.hiddenStartedAt+privateValue.duration)action({type:'explode'})},[Math.floor(now/200),g.phase,g.result,busy]);
 const light=g.engine==='light'&&g.timer&&g.phase==='active'?lightAt(g,now):null;const lightMine=light&&inMatch&&(!['1v2','1v3'].includes(g.format)||sideOf(g,uid)===1);
 useEffect(()=>{if(!unlock&&!audioEnabled)return;const sound=lightMine?'light-'+light.index:g.exploded?'explosion':g.timer&&timerLeft(g.timer,now)===0?'end-'+g.timer.startedAt:'';if(sound&&lastSound.current!==sound){lastSound.current=sound;battleSound(lightMine?light.color:g.exploded?'Explosion':'Time').catch(()=>{})}},[light?.index,g.exploded,g.timer&&timerLeft(g.timer,now)===0,unlock]);
 useEffect(()=>{if((!unlock&&!audioEnabled)||g.phase!=='active'||g.result||!['bomb','potato'].includes(g.engine)||g.engine==='bomb'&&g.timer?.pausedAt||g.engine==='potato'&&(!g.hiddenStartedAt||g.exploded))return;const interval=setInterval(()=>battleSound('Tick').catch(()=>{}),1000);return()=>clearInterval(interval)},[g.engine,g.phase,g.result,g.timer?.pausedAt,g.hiddenStartedAt,g.exploded,unlock]);
 const send=a=>!busy&&action(a);const btn=(label,a,enabled=host)=>enabled&&<button type="button" disabled={busy} onClick={()=>a.type==='reroll'?(yes('All players agreed to abandon this selection and reroll?')&&send(a)):send(a)}>{label}</button>;
 const submit=async value=>{if(!keys[uid])return;const c=await commitment(uid,value,keys[uid]);send({type:'commit',commit:c})};
 if(g.phase==='ready')return <div className="bc-match"><Teams g={g} names={names}/><Rules g={g}/>{btn('Agreed setting reroll',{type:'reroll',confirmed:true},host&&['mode','arena'].includes(g.engine))}{btn('Start this match',{type:'start'})}</div>;
 if(g.result&&!correction)return <div className="bc-match"><h3>{g.sprint||CHALLENGE_BY_ID[g.challengeId].name}</h3>{now<g.result.revealAt?<p>Result incoming…</p>:g.result.placements.map((ids,i)=><p key={i}>{i===0?'Leading: ':''}{ids.map(names).join(' + ')}</p>)}{host&&<button onClick={()=>setCorrection(true)}>Correct result</button>}{btn('Undo last input',{type:'undo'},host&&!!g.history?.length)}{host&&g.matches&&Object.entries(g.matches).filter(([,m])=>m.result).map(([id])=><button key={id} onClick={()=>send({type:'reopenMatch',matchId:id})}>Reopen {id}</button>)}</div>;
 if(correction)return <div className="bc-match"><h3>Correct result</h3><p>This preserves teams and random selections.</p><Placement g={g} names={names} allowDraw override onSubmit={(placements)=>{send({type:'manualResult',placements,override:true});setCorrection(false)}}/>{btn('Undo last input',{type:'undo'},host&&!!g.history?.length)}<button onClick={()=>setCorrection(false)}>Back</button></div>;
 if(g.phase==='tiebreak')return <div className="bc-match"><h3>Tiebreak</h3><p>{(g.tieGroups||[]).map(ids=>ids.map(names).join(' / ')).join(' · ')} take the next tiebreak attempt. Other placements stay fixed.</p>{btn('Start tiebreak',{type:'tiebreak'})}</div>;
 return <div className={'bc-match '+(lightMine?'bc-light-'+light.color:'')}>
 {privateError&&<p role="alert">{privateError}</p>}{lightMine&&<div aria-hidden="true" className={'bc-signal bc-signal-'+light.color}/>}<h3>{g.sprint||CHALLENGE_BY_ID[g.challengeId].name}</h3><Teams g={g} names={names}/><details><summary>Review rules</summary><Rules g={g}/></details>
 <p>Round {g.round||1}{g.level?' · Level '+g.level:''}</p>{g.setting&&<h3>{g.setting}</h3>}{g.mechanic&&<h3>{g.mechanic.name} · {g.mechanic.difficulty}</h3>}{g.draft&&<div className="bc-grid">{g.draft.map((m,i)=><div key={i}>{m.difficulty}: {m.name}<small>{g.engine==='draft'?i+1+' mini-points':''}</small></div>)}</div>}
 {g.timer&&g.engine!=='light'&&g.engine!=='bomb'&&<output className="bc-timer">{g.timer.duration==null?fmt(timerElapsed(g.timer,now)):fmt(timerLeft(g.timer,now))}{g.timer.pausedAt?' · Paused':''}{now<g.timer.startedAt?' · Get ready':''}</output>}
 {['light','bomb','potato'].includes(g.engine)&&<button onClick={()=>{setUnlock(true);battleSound('Ready')}}>Enable sound on this device</button>}
 {lightMine&&<h2>{light.color.toUpperCase()}</h2>}{light&&!lightMine&&inMatch&&<p>You are unrestricted.</p>}
 {['manual','sprintJudge'].includes(g.engine)&&host&&<Placement g={g} names={names} allowDraw={([2,4].includes(n)&&['1v2','1v3'].includes(g.format))} onSubmit={placements=>send({type:'manualResult',placements})}/>}
 {['mechanic','draft','mode','arena','light'].includes(g.engine)&&<>{btn('Agreed reroll',{type:'reroll',confirmed:true},host&&['mechanic','draft'].includes(g.engine))}{host&&<Placement g={g} names={names} onSubmit={placements=>send({type:'manualResult',placements})}/>}</>}
 {['tournament','potatoTournament'].includes(g.engine)&&<>
 {g.stage==='placementChoice'&&<><p>Final and third-place match are ready.</p>{['both','final','third'].map(mode=><span key={mode}>{btn(mode==='both'?'Play simultaneously':mode+' first',{type:'placementMode',mode})}</span>)}</>}
 <div className="bc-grid">{Object.entries(g.matches||{}).filter(([id])=>g.stage==='opening'?id==='opening':g.stage==='semis'?['a','b'].includes(id):['final','third'].includes(id)).map(([id,m])=>{const waiting=g.stage==='placementChoice'||g.stage==='placements'&&g.playMode!=='both'&&id!==g.playMode&&!g.matches[g.playMode]?.result;return <section key={id}><h3>{id==='opening'?'Opening 2v2':id==='a'?'Semifinal A':id==='b'?'Semifinal B':id==='third'?'Third place':'Final'}</h3>{waiting?<p>Waiting / Up next — {m.ids.map(names).join(' vs ')}</p>:<ChallengeGame g={m} uid={uid} host={host} hostId={hostId} names={names} keys={keys} busy={busy} action={a=>send({type:'matchAction',matchId:id,action:a})}/>}</section>})}</div></>}
 {g.engine==='sprintScore'&&(['1v1v1','1v1v1v1'].includes(g.format)?g.tieGroups?.flat()||g.sprintSubmitters:g.sprintSubmitters).map(id=><div key={id}><strong>{names(id)}{g.format==='2v2'&&g.sprint==='Pinch Sprint'?' (team pinch)':''}</strong><p>Attempts: {(g.entries?.[id]||[]).join(', ')||'None'}</p>{mine(id)&&((g.entries?.[id]?.length||0)<(g.tieGroups?1:g.sprintAttempts))&&(g.sprint==='Crossbar Sprint'?<>{btn('Hit',{type:'attempt',playerId:id,value:1},true)}{btn('Miss',{type:'attempt',playerId:id,value:0},true)}</>:<Num label="Goal KPH (0 = miss)" disabled={busy} onSubmit={value=>send({type:'attempt',playerId:id,value})}/>)}</div>)}
 {g.engine==='numeric'&&!(n===11&&g.format==='1v1')&&<><h3>{g.target?'Target: '+g.target+' KPH':'Enter attempts'}</h3>{g.ids.filter(id=>!g.tieGroups||g.tieGroups.flat().includes(id)).filter(id=>![61,62].includes(n)||g.sides.some(s=>s[0]===id)).map(id=><div key={id}><strong>{names(id)}</strong><p>{(g.entries?.[id]||[]).join(' + ')||'No attempts yet'}</p>{mine(id)&&<Num label={n===65?'Goals':'KPH (0 = miss)'} integer={n===65} disabled={busy} onSubmit={value=>send({type:'attempt',playerId:id,value})}/>}</div>)}</>}
 {g.engine==='numeric'&&n===11&&g.format==='1v1'&&<>{g.ids.map(id=><div key={id}>{names(id)} {g.kuxir?.[id]===undefined?<>{btn('Scored',{type:'scored',playerId:id},mine(id))}{btn('Missed',{type:'missed',playerId:id},mine(id))}</>:g.kuxir[id]?'Scored':'Missed'}{g.kuxir?.[id]&&g.ids.every(x=>g.kuxir?.[x])&&mine(id)&&<Num label="Kuxir goal KPH" onSubmit={value=>send({type:'kph',playerId:id,value})}/>}</div>)}</>}
 {g.engine==='ladder'&&g.ids.map(id=><div key={id}><strong>{names(id)}</strong><p>Completed {g.ladders[id].level} · Misses {g.ladders[id].misses}/{n===12?3:2} {g.ladders[id].done?'— Finished':''}</p>{!g.ladders[id].done&&<>{btn('Made',{type:'made',playerId:id},mine(id))}{btn('Missed',{type:'miss',playerId:id},mine(id))}</>}</div>)}
 {g.engine==='reset2'&&alive.map(id=><div key={id}>{names(id)} — {g.roundInputs?.[id]===undefined?'Waiting':g.roundInputs[id]?'Made':'Missed'}{g.roundInputs?.[id]===undefined&&<>{btn('Made',{type:'made',playerId:id},mine(id))}{btn('Missed',{type:'miss',playerId:id},mine(id))}</>}</div>)}
 {['horse','chain','copySurvival'].includes(g.engine)&&<><p>Phase: {g.subphase} · {g.engine==='copySurvival'?'Survived '+g.survived:current?.startsWith('team')?g.sides[Number(current.at(-1))].map(names).join(' + '):names(current)}</p>{g.lives&&<p>{Object.entries(g.lives).map(([id,l])=>(id.startsWith('team')?id:names(id))+': '+l+' remaining').join(' · ')}</p>}{g.subphase==='copy'&&g.engine!=='chain'?(g.engine==='copySurvival'?g.sides[1]:g.required||[]).map(id=><div key={id}>{names(id)}{g.copies?.[id]===undefined?<>{btn('Copied',{type:'made',playerId:id})}{btn('Failed copy',{type:'miss',playerId:id})}</>:g.copies[id]?'Made':'Missed'}</div>):<>{btn('Made',{type:'made'})}{btn('Missed',{type:'miss'})}</>}</>}
 {g.engine==='survival'&&g.ids.map(id=><div key={id}>{names(id)}: {g.lives[id]} lives {btn('Lost a life',{type:'life',playerId:id},mine(id)&&g.lives[id]>0)}</div>)}
 {g.engine==='survival'&&host&&<BatchLife ids={alive} names={names} submit={ids=>send({type:'batchLife',ids})}/>}
 {g.engine==='ttt'&&<><p>{g.order.map(id=>names(id)+' = '+g.marks[id]).join(' · ')} · {n===52?'Turn: '+names(g.order[g.turn%2]):'Take turns verbally; only claim successful mechanics.'}</p><div className="bc-ttt">{Array.from({length:9},(_,i)=><button key={i} disabled={busy||!inMatch||n===52&&(!!g.tiles?.[i]||uid!==g.order[g.turn%2])||n===28&&g.tiles?.[i]&&g.tiles[i]!==uid} onClick={()=>{if(n===52||yes(g.tiles?.[i]?'Remove your mistaken marker?':'Did you successfully complete '+g.tileMechanics[i].name+'?'))send({type:'claim',tile:i})}}>{g.tiles?.[i]?g.marks[g.tiles[i]]:n===28?g.tileMechanics[i].name:'·'}</button>)}</div>{n===28&&host&&<select defaultValue="" onChange={e=>{if(e.target.value!==''&&yes('Both players agreed to reroll this unclaimed tile?'))send({type:'rerollTile',tile:Number(e.target.value)});e.target.value=''}}><option value="">Reroll unclaimed tile…</option>{Array.from({length:9},(_,i)=>!g.tiles?.[i]&&<option key={i} value={i}>Tile {i+1}</option>)}</select>}</>}
 {g.engine==='ttt'&&n===28&&btn('Agreed draw',{type:'manualResult',placements:[g.ids],override:true})}
 {g.engine==='tug'&&<><div className="bc-track"><span style={{left:(g.rope+g.limit)/(2*g.limit)*100+'%'}}>●</span></div><p>Marker: {g.rope} · Win endpoints ±{g.limit}</p>{g.ids.map(id=><div key={id}><strong>{names(id)}: {g.mechanics[id].name}</strong>{btn('Completed',{type:'complete',revision:g.mechanicVersions?.[id]||0},id===uid)}{btn('Reroll (1-space penalty)',{type:'rerollOwn',revision:g.mechanicVersions?.[id]||0},id===uid)}</div>)}</>}
 {g.engine==='bomb'&&<><div className="bc-track"><span style={{left:(bombPosition(g,now)+1)*50+'%'}}>💣</span></div><p>Bomb moving toward {g.sides[g.bomb.direction<0?0:1].map(names).join(' + ')}</p>{btn('Valid unused answer — Reverse bomb',{type:'reverse',revision:g.bomb.version},inMatch&&sideOf(g,uid)===(g.bomb.direction<0?0:1))}</>}
 {g.engine==='alphabet'&&<><h2>{g.letter}</h2>{g.ids.map(id=><div key={id}>{names(id)}: {g.scores[id]} {btn('+1 successful mechanic',{type:'point',playerId:id})}</div>)}{btn('Agreed letter reroll',{type:'reroll',confirmed:true})}</>}
 {g.engine==='names'&&<><h3>{names(current)} — Name a {n===47?'car':'pro / creator'}</h3>{btn('I said a valid unused answer',{type:'pass'},mine(current))}{host&&<details><summary>Dispute / invalid answer</summary>{alive.map(id=><span key={id}>{btn('Mark '+names(id)+' invalid',{type:'invalidAnswer',playerId:id})}</span>)}<Validity category={n===47?'car':'person'}/></details>}</>}
 {g.engine==='speedladder'&&<><p>{names(current)}: {g.subphase==='set'?'Set a fresh baseline':'Beat the baseline'}</p>{g.subphase==='set'?btn('Baseline set',{type:'baseline'},mine(current)):<>{btn('Higher',{type:'higher'},mine(current))}{btn('Failed',{type:'failed'},mine(current))}</>}<p>{g.ids.map(id=>names(id)+': '+g.lives[id]+' hearts').join(' · ')}</p></>}
 {['reverseSpeed','sprint','airdribble','gauntlet'].includes(g.engine)&&<><p>Current player: {names(current)} {g.baseline!=null?' · Baseline: '+g.baseline+' KPH':''}</p>
 {g.engine==='sprint'&&!['1v2','1v3'].includes(g.format)?g.ids.map(id=><div key={id}>{names(id)}{g.entries?.[id]?' — Finish submitted':btn('Finished shot #10',{type:'finish',playerId:id},mine(id))}</div>):<>
 {!g.timer&&btn('Start run',{type:'timerStart'},g.engine==='airdribble'?inMatch&&uid!==current||host:mine(current))}
 {g.timer&&!g.timer.pausedAt&&g.engine!=='gauntlet'&&btn(g.engine==='reverseSpeed'?'Goal scored — Stop timer':'Stop timer',{type:'timerStop'},g.engine==='airdribble'?mine(g.operator):mine(current))}
 {g.engine==='gauntlet'&&g.timer&&btn('Complete '+['Easy','Medium','Hard'][g.laps?.[current]?.length||0],{type:'complete'},mine(current))}
 {g.timer?.pausedAt&&(g.engine==='reverseSpeed'?mine(current)&&<Num label="Actual goal KPH" disabled={busy} onSubmit={value=>send({type:'kph',value})}/>:<>{btn('Valid goal / Submit time',{type:'submitRun'},g.engine==='airdribble'?mine(g.operator):mine(current))}{g.engine==='airdribble'&&btn('Failed attempt (0)',{type:'submitRun',failed:true},mine(g.operator))}</>)}
 {btn('Redo current run',{type:'redoRun'})}</>}</>}
 {g.engine==='endurance'&&<>{!g.timer&&btn('Start '+names(current)+' run',{type:'timerStart'},mine(current))}{g.timer&&timerLeft(g.timer,now)===0&&g.ids.filter(id=>!['1v2','1v3'].includes(g.format)||id===current).map(id=><div key={id}>{names(id)}: {g.entries?.[id]??'Waiting'}{mine(id)&&<Num label="Shots completed" integer disabled={busy} onSubmit={value=>send({type:'count',playerId:id,value})}/>}</div>)}</>}
 {g.engine==='series'&&!g.matches?.current&&<><p>{(g.overtime?g.tiebreakPair:g.pairs[g.segment])?.map(names).join(' vs ')}</p><p>{g.overtime?'Next qualifying score wins':'Segment '+(g.segment+1)+' / '+g.pairs.length} · Totals: {(g.totals||[0,0]).join(' – ')}</p>{host&&(g.overtime||g.seriesMode==='wins'?<>{btn('Solo / Team A won',{type:'segment',side:0})}{btn('Team member / Team B won',{type:'segment',side:1})}</>:<PairScores onSubmit={(left,right)=>send({type:'segment',left,right})} busy={busy}/>)}</>}
 {g.engine==='series'&&g.matches?.current&&<><p>Mini-match {g.segment+1} · Side score {(g.totals||[0,0]).join(' – ')}</p><ChallengeGame g={g.matches.current} uid={uid} host={host} hostId={hostId} names={names} keys={keys} busy={busy} action={a=>send({type:'matchAction',matchId:'current',action:a})}/>{g.matches.current.result&&btn('Continue series',{type:'nextSegment'})}</>}
 {g.engine==='triathlon'&&<><p>Event {g.eventIndex+1}: {g.events[g.eventIndex]}</p><p>{g.events.join(' → ')}</p><p>{g.ids.map(id=>names(id)+': '+g.scores[id]).join(' · ')}</p><ChallengeGame g={g.matches.current} uid={uid} host={host} hostId={hostId} names={names} keys={keys} busy={busy} action={a=>send({type:'matchAction',matchId:'current',action:a})}/>{g.matches.current.result&&btn('Confirm event result & Continue',{type:'nextEvent'})}</>}
 {g.engine==='kickoff'&&<><p>{g.pairs[g.pairIndex]?.map(names).join(' vs ')} · Kickoff {g.kickoffCount+1}/{g.kickoffLimit}</p>{g.pairs[g.pairIndex]?.map(id=><span key={id}>{btn(names(id)+' won kickoff',{type:'kickoff',playerId:id})}</span>)}</>}
 {['goals','timedGoals'].includes(g.engine)&&<><p>{g.sides.map((s,i)=>s.map(names).join(' + ')+': '+s.reduce((t,id)=>t+(g.scores[id]||0),0)).join(' · ')}</p>{g.phase==='overtime'&&<h3>Next qualifying score wins</h3>}{g.sides.map((s,i)=>((![66,76].includes(n)||i===1)&&(![67,77].includes(n)||i===0))&&<span key={i}>{btn(n===83&&i===0?'Solo hit back wall':s.map(names).join(' + ')+' scored',{type:'goal',side:i})}</span>)}</>}
 {g.engine==='hunt'&&<><h3>{n===71&&g.subphase==='headstart'?'Runner head start — Hunters wait':'Hunt active'}</h3>{n===71?btn('Runner demoed',{type:'demo'},host&&g.subphase==='hunt'):g.sides[1].filter(id=>!g.out?.includes(id)).map(id=><span key={id}>{btn(names(id)+' demoed',{type:'demo',playerId:id})}</span>)}</>}
 {g.engine==='pressure'&&<>{g.normalAttacksDone&&host&&<><p>Normal possessions complete. If tied, use paired pressure attempts before selecting a winner.</p><Placement g={g} names={names} onSubmit={placements=>send({type:'manualResult',placements})}/></>}<p>Attacking: {g.sides[g.turn%2].map(names).join(' + ')}</p>{[15,10,5].map(seconds=><span key={seconds}>{btn('Start '+seconds+'s',{type:'timerStart',seconds},host||g.sides[g.turn%2].includes(uid))}</span>)}{(host||g.sides[g.turn%2].includes(uid))&&<button onClick={()=>yes('Have you completed all three time limits?')&&send({type:'endTurn',confirmed:true})}>End attacking turn</button>}</>}
 {g.engine==='heads'&&g.sides.map((s,i)=><div key={i}>{s.map(names).join(' + ')}{btn('Side succeeded',{type:'sideResult',side:i,made:true})}{btn('Side failed',{type:'sideResult',side:i,made:false})}</div>)}
 {g.engine==='combo'&&g.ids.map(id=><div key={id}><h4>{names(id)}</h4>{g.combo[sideOf(g,id)].map((m,i)=><p key={i}>{m.name} {Object.hasOwn(g.comboInputs||{},id+'_'+i)?g.comboInputs[id+'_'+i]?'Made':'Missed':<>{btn('Made first try',{type:'combo',playerId:id,index:i,made:true},mine(id))}{btn('Missed',{type:'combo',playerId:id,index:i,made:false},mine(id))}</>}</p>)}</div>)}
 {g.engine==='relay'&&<><p>Solo: One-bounce Kuxir. Trio: Easy → Medium → Hard.</p>{btn('Solo completed',{type:'complete'},uid===g.sides[0][0])}{g.sides[1].map((id,i)=><p key={id}>{names(id)} — {g.draft[i].name} {i<g.turn?'Done':i===g.turn?btn('Completed relay mechanic',{type:'complete'},uid===id):'Waiting'}</p>)}</>}
 {g.engine==='shark'&&<><h3>Crossing {g.crossing}/{g.crossings} · {g.crossing%2?'Blue → Orange':'Orange → Blue'}</h3>{g.phase==='regroup'?<>{btn('Regrouped — Start next crossing',{type:'nextCrossing'})}</>:g.sides[1].map(id=><p key={id}>{names(id)}: {g.out?.includes(id)?'Out':g.safe?.[id]?'Safe':<>{btn('Reached safety',{type:'safe',playerId:id},mine(id))}{btn('Demoed',{type:'eliminate',playerId:id},mine(id))}</>}</p>)}</>}
 {SECRET_ENGINES.includes(g.engine)&&<SecretControls g={g} uid={uid} host={host} hostId={hostId} names={names} busy={busy} privateValue={privateValue} send={send} submit={submit}/>}
 {host&&<details className="bc-recovery"><summary>Match recovery</summary>{g.matches&&Object.entries(g.matches).filter(([,m])=>m.result).map(([id])=><button key={id} onClick={()=>yes('Reopen '+id+'? Later match progress may need replaying; game selections stay fixed.')&&send({type:'reopenMatch',matchId:id})}>Reopen {id}</button>)}{btn('Undo last input',{type:'undo'},!!g.history?.length)}{g.timer&&<>{g.timer.pausedAt?btn('Resume play',{type:'resume'}):btn('Pause for setup / dispute',{type:'pause'})}</>}<button disabled={busy} onClick={()=>yes('Restart this Challenge? Its progress and random choices will reset.')&&send({type:'restart',confirmed:true})}>Restart Challenge</button><button onClick={()=>setCorrection(true)}>Correct / manually resolve result</button></details>}
 </div>
}
function PairScores({onSubmit,busy}){const [left,setLeft]=useState(''),[right,setRight]=useState('');return <form onSubmit={e=>{e.preventDefault();if(left!==''&&right!=='')onSubmit(Number(left),Number(right))}}><label>Solo / Team A goals<input required min="0" step="1" type="number" value={left} onChange={e=>setLeft(e.target.value)}/></label><label>Opponent / Team B goals<input required min="0" step="1" type="number" value={right} onChange={e=>setRight(e.target.value)}/></label><button disabled={busy||left===''||right===''}>Submit segment scores</button></form>}
function SecretControls({g,uid,host,hostId,names,busy,privateValue,send,submit}){const n=parseInt(g.challengeId.split('-')[1]),p=secretParticipants(g),locked=!!g.commits?.[uid],[choice,setChoice]=useState('');const btn=(label,a,enabled=host)=>enabled&&<button disabled={busy} onClick={()=>a.type==='reroll'?(yes('All players agreed to abandon this selection and reroll?')&&send(a)):send(a)}>{label}</button>;const needDeal=['target','boss','luck','imposter','potato'].includes(g.engine)&&!Object.keys(g.sealed||{}).length;
 return <div className="bc-secret">{needDeal?<>{btn('Deal private information',{type:'deal'})}{!host&&<p>Waiting for the Battle Host to deal…</p>}</>:<>
 {g.engine==='luck'&&<>{privateValue&&!locked&&<div className="bc-private"><h3>Your secret number: {privateValue.first}</h3><button disabled={busy} onClick={()=>submit(privateValue.first)}>Bank</button><button disabled={busy} onClick={()=>submit(privateValue.second)}>Risk — discard this and keep one new number</button></div>}{locked&&<p>Your decision is locked.</p>}{g.ids.every(id=>Object.hasOwn(g.reveals||{},id))&&btn('Reveal results',{type:'luckReveal'})}</>}
 {g.engine==='auction'&&<><p>Round {g.round}/3 · First success gets 1 mini-point and ends the round.</p>{g.subphase==='bid'&&!Object.keys(g.commits||{}).length&&btn('Draw another Hard mechanic',{type:'rerollHard'})}{g.subphase==='bid'&&p.includes(uid)&&!locked&&<select value="" onChange={e=>e.target.value&&submit(Number(e.target.value))}><option value="">Secret bid…</option>{[1,2,3,4,5].map(v=><option key={v}>{v}</option>)}</select>}{g.subphase==='attempt'&&<><p>{names(g.bidOrder[g.bidIndex])}: up to {g.reveals[g.bidOrder[g.bidIndex]]} attempts.</p>{btn('Succeeded',{type:'auctionAttempt',made:true},host||uid===g.bidOrder[g.bidIndex])}{btn('Failed all bid attempts',{type:'auctionAttempt',made:false},host||uid===g.bidOrder[g.bidIndex])}</>}{g.subphase==='roundResult'&&btn('Continue',{type:'nextRound'})}</>}
 {g.engine==='guess'&&<><p>Shooter: {names(g.shooters[g.shot])} · Shot {g.shot+1}/{g.shooters.length}. Pause Rocket League before the replay reveals speed.</p>{n===39&&g.estimate===undefined&&(host||uid===g.shooters[g.shot])&&<Num label="Shooter's announced estimate" onSubmit={value=>send({type:'estimate',value})}/>} {g.estimate!==undefined&&<p>Estimate: {g.estimate} KPH</p>}{g.subphase==='guess'&&p.includes(uid)&&!locked&&(n===39?g.estimate!==undefined&&<><button onClick={()=>submit('higher')}>Higher</button><button onClick={()=>submit('lower')}>Lower</button></>:<Num label="Your secret KPH guess" onSubmit={submit} disabled={busy}/>)}{g.subphase==='actual'&&host&&<Num label="Actual Rocket League KPH" onSubmit={value=>send({type:'actual',value})} disabled={busy}/>} {g.subphase==='shotResult'&&<><p>Actual: {g.actual} KPH</p>{host&&<details><summary>Correct actual KPH (guesses stay locked)</summary><Num label="Correct actual KPH" onSubmit={value=>send({type:'actual',value})}/></details>}{Object.entries(g.scores).map(([id,s])=><p key={id}>{names(id)}: {s} {n===30?'total error':'points'}</p>)}{btn('Continue',{type:'nextShot'})}</>}</>}
 {g.engine==='target'&&<><p>Attacking: {g.sides[g.turn%2].map(names).join(' + ')} · Possession {g.shot+1}</p>{privateValue?.target&&g.sides[g.turn%2].includes(uid)&&<div className="bc-private">Your secret target: <strong>{privateValue.target}</strong>. Do not show defenders.</div>}{g.subphase==='attack'&&g.sides[g.turn%2].includes(uid)&&[2,1,0].map(v=><button key={v} disabled={busy} onClick={()=>yes('Submit '+v+' attacking points?')&&send({type:'attackResult',value:v})}>{v===2?'Scored + hit target':v===1?'Scored + missed target':'Missed / Saved'}</button>)}{g.subphase==='predict'&&p.includes(uid)&&!locked&&<select value="" onChange={e=>e.target.value&&yes('Lock prediction: '+e.target.value+'?')&&submit(e.target.value)}><option value="">Predict secret target…</option>{TARGETS.map(t=><option key={t}>{t}</option>)}</select>}{g.subphase==='revealTarget'&&privateValue?.target&&g.sides[g.turn%2].includes(uid)&&btn('Reveal locked target',{type:'targetReveal',target:privateValue.target},true)}{g.subphase==='shotResult'&&<><p>Target: {g.target} · Prediction: {Object.values(g.reveals||{}).join(', ')}</p><p>{g.sides.map(s=>s.map(names).join(' + ')+': '+g.scores[s[0]]).join(' · ')}</p>{btn('Next possession',{type:'nextShot'})}</>}</>}
 {g.engine==='boss'&&<><p>Round {g.round}/{g.totalRounds}. Boss: {names(g.sides[0][0])}</p>{g.subphase==='bossChoose'&&privateValue?.options&&uid===g.sides[0][0]&&privateValue.options.map(m=><button key={m.id} disabled={busy} onClick={()=>yes('Choose '+m.name+'?')&&send({type:'bossChoose',value:m.id})}>{m.name}</button>)}{g.subphase==='challenger'&&(host||g.sides[1].includes(uid))&&g.sides[1].filter(id=>!g.out?.includes(id)).map((id,_,alive)=><button key={id} disabled={busy||alive.length>1&&g.lastChallenger===id} onClick={()=>send({type:'challenger',playerId:id})}>Choose {names(id)}</button>)}{g.subphase==='attempt'&&<><p>{names(g.challenger)} · Attempt {g.attempt}/2</p>{btn('Made',{type:'bossAttempt',made:true},host||uid===g.challenger)}{btn('Missed',{type:'bossAttempt',made:false},host||uid===g.challenger)}</>}{g.subphase==='roundResult'&&btn('Next round',{type:'nextRound'})}<p>Out: {(g.out||[]).map(names).join(', ')||'Nobody'}</p></>}
 {g.engine==='imposter'&&<>{privateValue&&<details className="bc-private"><summary>Show my private role</summary><strong>{privateValue.role==='imposter'?'IMPOSTER — blend in':'NON-IMPOSTER'}</strong>{privateValue.prompt&&<p>Secret prompt: {privateValue.prompt.name}</p>}</details>}{g.subphase==='roles'&&btn('Everyone checked roles — Begin clues',{type:'rolesReady'})}{g.subphase==='clues'&&<><p>{names(g.order[g.turn])}: {n===80?'take your shot':'give your verbal clue'}.</p>{btn(n===80?'Shot complete':'Clue given',{type:'clue'},host||uid===g.order[g.turn])}</>}{g.subphase==='discussion'&&<><h3>Discuss who the Imposter is</h3>{btn('Begin secret vote',{type:'voteStart'})}</>}{g.subphase==='vote'&&!locked&&<select value="" onChange={e=>e.target.value&&yes('Lock your vote?')&&submit(e.target.value)}><option value="">Vote for another player…</option>{g.ids.filter(id=>id!==uid).map(id=><option key={id} value={id}>{names(id)}</option>)}</select>}{g.subphase==='accused'&&<><p>Accused: {names(g.accused)}</p>{uid===g.accused&&privateValue&&btn('Reveal my role',{type:'accusedRole',imposter:privateValue.role==='imposter'},true)}</>}{g.subphase==='identify'&&privateValue?.role==='imposter'&&btn('Reveal that I was the Imposter',{type:'identify',imposter:true},true)}{g.subphase==='finalGuess'&&uid===g.imposter&&<><p>One exact prompt guess to steal the win.</p><input placeholder="Filter answers…" value={choice} onChange={e=>setChoice(e.target.value)}/><select value="" onChange={e=>e.target.value&&yes('Submit your ONE final guess?')&&send({type:'finalGuess',value:e.target.value})}><option value="">Choose your final answer…</option>{(n===81?WORDS:[...PARTY_MECHANICS,...REQUIREMENTS.map(name=>({id:name,name})),...[70,80,90,100,110,120,130,140].map(k=>({id:String(k),name:k+' KPH'}))]).filter(v=>v.name.toLowerCase().includes(choice.toLowerCase())).map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></>}{g.subphase==='verify'&&privateValue?.prompt&&btn('Reveal prompt and resolve guess',{type:'verify',prompt:privateValue.prompt},true)}</>}
 {g.engine==='potato'&&<><strong>SKIP ALL REPLAYS IMMEDIATELY.</strong>{!g.hiddenStartedAt?btn('Start Hot Potato',{type:'bombStart'}):g.exploded?<><h2>💥 EXPLOSION</h2><p>If ball was at center: play the kickoff and use the half it enters. No timer restart for this.</p>{g.sides.map((s,i)=><span key={i}>{btn(s.map(names).join(' + ')+' won',{type:'potatoResult',side:i})}</span>)}{btn('Ambiguous side — Retry',{type:'retryPotato'})}</>:<p>💣 Timer running. Stay ready.</p>}</>}
 {p.length>0&&['bid','guess','vote','predict','decide'].includes(g.subphase)&&<p>{p.map(id=>names(id)+': '+(g.commits?.[id]?'Locked':'Waiting')).join(' · ')}</p>}
 </>}</div>
}
function BatchLife({ids,names,submit}){const [selected,setSelected]=useState([]);return <details><summary>Simultaneous life losses</summary>{ids.map(id=><label key={id}><input type="checkbox" checked={selected.includes(id)} onChange={e=>setSelected(e.target.checked?[...selected,id]:selected.filter(x=>x!==id))}/>{names(id)}</label>)}<button disabled={!selected.length} onClick={()=>{if(yes('Confirm these life losses happened simultaneously?')){submit(selected);setSelected([])}}}>Record together</button></details>}
function Validity({category}){const [value,setValue]=useState('');const normalized=value.toLowerCase().replace(/[^a-z0-9]/g,'');const valid=(category==='car'?CAR_NAMES:PEOPLE).some(v=>v.toLowerCase().replace(/[^a-z0-9]/g,'')===normalized);return <div><p>Pause the timer before checking. This reference list is not exhaustive; resolve unlisted names verbally.</p><input value={value} onChange={e=>setValue(e.target.value)} placeholder="Disputed name"/>{value&&<p>{valid?'In approved reference list':'Not in reference list — host resolves'}</p>}</div>}
