import { useEffect, useRef, useState } from 'react'
import { createPortal } from 'react-dom'
import { battleSound, enableBattleAudio, battleAudioReady, stopBattleSpeech } from './partyBattleAudio'
import { playerRules, needsBattleAudio } from './partyChallengeRules'
import PartyBattleRoulette from './PartyBattleRoulette'
import { CHALLENGE_BY_ID, PARTY_CHALLENGES, FORMAT_SIZES } from './partyChallengeCatalog'
import { timerElapsed, timerLeft, bombPosition, lightAt, sideOf, TARGETS, WORDS, REQUIREMENTS, CAR_NAMES, PEOPLE, CHALLENGE_REWARDS, rewardDistribution, drawAllowed, seeded, shuffle } from './partyChallengeEngine'
import { SECRET_ENGINES, secretParticipants } from './partyChallengeSecretEngine'
import { unseal, commitment } from './partyChallengeSecrets'
import { registerBattleKey, sendChallengeAction, confirmChallengeRewards, cancelChallenge, startRoundChallenge, launchChallengeDevTest, challengeNow } from './partyChallengeTransport'
import { PARTY_MECHANICS } from './partyMechanics'
import './partyChallenge.css'
export { battleSound } from './partyBattleAudio'
export function BattleAudioCheck({onReady}){const [status,setStatus]=useState(battleAudioReady()?'Sound enabled on this device.':'');return <div className="bc-audio"><button type="button" onClick={()=>enableBattleAudio().then(()=>{setStatus('Sound enabled. Make sure you heard the tone.');onReady?.()}).catch(e=>setStatus(e.message))}>Enable / test sound</button><small role="status">{status||'This challenge uses sound. Each participating device: tap to enable it.'}</small></div>}
export default function PartyChallenge(props){const dialog=useRef(null);useEffect(()=>{const before=document.activeElement;dialog.current?.focus();return()=>{before?.focus?.()}},[]);const content=<div className="bc-backdrop"><div className="bc-dialog" role="dialog" aria-modal="true" aria-label="Battle" tabIndex={-1} ref={dialog} onKeyDown={e=>{if(e.key!=='Tab')return;const nodes=[...dialog.current.querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled),summary,[tabindex="0"]')].filter(n=>n.getClientRects().length);if(!nodes.length){e.preventDefault();return}if(e.shiftKey&&document.activeElement===nodes[0]){e.preventDefault();nodes.at(-1).focus()}else if(!e.shiftKey&&document.activeElement===nodes.at(-1)){e.preventDefault();nodes[0].focus()}}}><BattleContent {...props}/></div></div>;return typeof document==='undefined'?content:createPortal(content,document.body)}
function rouletteOptions(b,names){
 if(b.stage==='formatReveal')return Object.entries(FORMAT_SIZES).filter(([,n])=>n===b.participantIds.length).map(([value])=>({value,label:value}));
 if(b.stage==='challengeReveal'){const pool=PARTY_CHALLENGES.filter(c=>c.formats.includes(b.format));const r=seeded((Number(b.seed)||1)+b.version);const others=shuffle(pool.filter(c=>c.id!==b.challengeId),r).slice(0,5);return shuffle([CHALLENGE_BY_ID[b.challengeId],...others],r).map(c=>({value:c.id,label:c.name}))}
 const ids=b.game.ids;let teams;if(b.format==='2v2')teams=ids.slice(1).map(id=>[[ids[0],id],ids.filter(x=>x!==ids[0]&&x!==id)]);else teams=ids.map(id=>[[id],ids.filter(x=>x!==id)]);
 return teams.map(s=>({value:teamKey(s),label:s.map(t=>t.map(names).join(' + ')).join(' vs ')}));
}
function teamKey(sides){return sides.map(s=>[...s].sort().join(',')).sort().join('|')}
const yes=text=>window.confirm(text)
function useNow(enabled=true){const [now,setNow]=useState(challengeNow());useEffect(()=>{if(!enabled)return;setNow(challengeNow());const refresh=()=>setNow(challengeNow());const t=setInterval(refresh,100);window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);return()=>{clearInterval(t);window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh)}},[enabled]);return enabled?now:challengeNow()}
const fmt=n=>(Math.max(0,n)/1000).toFixed(1)+'s'
function Num({label='Value',onSubmit,integer=false,disabled=false}){const [v,setV]=useState('');return <form className="bc-inline" onSubmit={e=>{e.preventDefault();if(v!==''&&Number.isFinite(Number(v))&&Number(v)>=0&&(!integer||Number.isInteger(Number(v)))){onSubmit(Number(v));setV('')}}}><label>{label}<input required type="number" min="0" step={integer?'1':'any'} value={v} disabled={disabled} onChange={e=>setV(e.target.value)}/></label><button disabled={disabled||v===''}>Submit</button></form>}
function Placement({g,names,onSubmit,allowDraw=false,override=false}){const [ranks,setRanks]=useState({});const team=g.sides.length===2&&!['1v1v1','1v1v1v1'].includes(g.format);return <div className="bc-controls"><h3>Enter Battle Result</h3>{team?g.sides.map((s,i)=><button key={i} onClick={()=>onSubmit([s,g.sides[1-i]],override)}>{s.map(names).join(' + ')} Won</button>):<><p>Enter placements. Use equal ranks only when this Challenge permits ties.</p>{g.ids.map(id=><label key={id}>{names(id)}<select value={ranks[id]||''} onChange={e=>setRanks({...ranks,[id]:Number(e.target.value)})}><option value="">Place…</option>{g.ids.map((_,i)=><option key={i} value={i+1}>{i+1}</option>)}</select></label>)}<button disabled={!g.ids.every(id=>ranks[id])} onClick={()=>{const groups=Object.values(g.ids.reduce((o,id)=>{(o[ranks[id]]||=[]).push(id);return o},{}));onSubmit(groups,override)}}>Submit placements</button></>}{allowDraw&&<button onClick={()=>onSubmit([g.ids],override)}>Draw</button>}</div>}
export function ChallengeDev({room,roomCode,clientId,runAction,busy=false}){const [id,setId]=useState(PARTY_CHALLENGES[0].id),[format,setFormat]=useState('1v1');const c=CHALLENGE_BY_ID[id],count=Object.keys(room.players||{}).length;return <section className="bc-dev"><h3>Challenge Test Lab</h3><label>Challenge<select value={id} onChange={e=>{setId(e.target.value);setFormat(CHALLENGE_BY_ID[e.target.value].formats[0])}}>{PARTY_CHALLENGES.map(c=><option value={c.id} key={c.id}>{c.number}. {c.name}</option>)}</select></label><label>Format<select value={format} onChange={e=>setFormat(e.target.value)}>{c.formats.map(f=><option key={f} value={f} disabled={FORMAT_SIZES[f]>count}>{f}{FORMAT_SIZES[f]>count?' — needs '+FORMAT_SIZES[f]+' players':''}</option>)}</select></label><button disabled={busy||FORMAT_SIZES[format]>count} onClick={()=>yes('Launch this test Battle? This replaces the current test turn. Rewards affect this room.')&&runAction(()=>launchChallengeDevTest(roomCode,clientId,id,format))}>Launch selected Battle</button></section>}
function BattleContent({room,roomCode,clientId,onNextRound,onLeave}){const b=room.phase==='round-complete'?room.roundBattle:room.turnState?.battle;const [busy,setBusy]=useState(false),[error,setError]=useState('');const isHost=b?b.hostId===clientId:room.hostId===clientId;const names=id=>room.players?.[id]?.name||'Departed player';
 useEffect(()=>{registerBattleKey(roomCode,clientId).catch(e=>setError(e.message))},[roomCode,clientId]);
 async function run(fn){if(busy)return;setBusy(true);setError('');try{await fn()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const act=a=>run(()=>sendChallengeAction(roomCode,clientId,b.id,a));const missing=b?.participantIds?.some(id=>!room.players?.[id]||room.departedPlayers?.[id]);
 if(!b)return <section className="bc">{onLeave&&<button onClick={onLeave}>{room.hostId===clientId?'End game':'Leave game'}</button>}<h2>Round {room.currentRound} Challenge</h2><p>Everyone participates. The format, Challenge, and teams are selected in that order.</p>{isHost?<button disabled={busy} onClick={()=>run(()=>startRoundChallenge(roomCode,clientId))}>Select round Challenge</button>:<p>Waiting for the host…</p>}{error&&<p role="alert">{error}</p>}</section>;
 if(b.status==='resolved')return <section className="bc">{onLeave&&<button onClick={onLeave}>{room.hostId===clientId?'End game':'Leave game'}</button>}<h2>{b.name}</h2><p>{b.resultMessage}</p>{b.rewards&&Object.entries(b.rewards).map(([id,n])=><p key={id}>{names(id)}: +{n} Tokens</p>)}{room.phase==='round-complete'&&isHost&&<button onClick={onNextRound}>Continue {room.currentRound>=room.settings.rounds?'to final standings':'to next round'}</button>}</section>;
 return <section className="bc" aria-label="Party Challenge">{onLeave&&<button className="bc-leave" onClick={onLeave}>{room.hostId===clientId?'End game':'Leave game'}</button>}<p className="bc-eyebrow">{b.source==='round-end'?'Round Challenge':b.source==='challenge-glove'?'Challenge Glove':'Battle'} · Host: {names(b.hostId)}</p>
 {b.stage!=='intro'&&<h2>{['rules','play'].includes(b.stage)?`Battle Card #${CHALLENGE_BY_ID[b.challengeId]?.number||''}`:b.stage==='intro'?'Battle!':'Battle selection'}</h2>}{['rules','play'].includes(b.stage)&&<h3 className="bc-card-title">{b.name}</h3>}{error&&<p role="alert" className="bc-error">{error} <button disabled={busy} onClick={()=>run(()=>registerBattleKey(roomCode,clientId))}>Retry connection</button></p>}{missing&&<p>A participant left. The host can cancel below and start a new Battle.</p>}
 {b.stage==='format'&&<><p>Choose the format, then lock in the participants before revealing the game.</p>{Object.entries(FORMAT_SIZES).map(([f,n])=><button disabled={!isHost||busy||n>b.participantIds.length} key={f} onClick={()=>act({type:'format',format:f})}>{f}</button>)}</>}
 {b.stage==='participants'&&<ParticipantPicker b={b} names={names} host={isHost} busy={busy} submit={sides=>act({type:'participants',sides})}/>}
 {b.stage==='intro'&&<div className="bc-intro"><span className="bc-burst">BATTLE!</span><p>{b.participantIds.map(names).join(' · ')}</p><p>Get ready for a Challenge.</p>{isHost?<button disabled={busy} onClick={()=>act({type:'next'})}>Let's go</button>:<p>Waiting for the Battle Host…</p>}</div>}
 {b.stage==='draw'&&<div className="bc-intro"><h3>{b.format}</h3><p>Next: select your game.</p>{isHost?<button disabled={busy} onClick={()=>act({type:'next'})}>Spin game roulette</button>:<p>Waiting for the Battle Host…</p>}</div>}
 {['formatReveal','challengeReveal','teamReveal'].includes(b.stage)&&<PartyBattleRoulette key={b.stage} title={b.stage==='formatReveal'?'Choose the format':b.stage==='challengeReveal'?'Choose the game':'Choose the teams'} options={rouletteOptions(b,names)} winner={b.stage==='formatReveal'?b.format:b.stage==='challengeReveal'?b.challengeId:teamKey(b.game.sides)} startedAt={b.revealStartedAt} host={isHost} busy={busy} onContinue={()=>act({type:'next'})}/>}
 {b.stage==='rules'&&<><Teams g={b.game} names={names}/><Rules g={b.game}/>{needsBattleAudio(b.game)&&<BattleAudioCheck/>}{isHost&&b.game.engine==='mode'&&<button onClick={()=>act({type:'game',action:{type:'reroll',confirmed:true}})}>Agreed setting reroll</button>}{isHost?<button disabled={busy} onClick={()=>act({type:'next'})}>Everyone ready — Play</button>:<p>Read the rules. Waiting for the Battle Host.</p>}</>}
 {b.stage==='play'&&<ChallengeGame g={b.game} uid={clientId} host={isHost} hostId={b.hostId} names={names} keys={room.battleKeys||{}} busy={busy} action={a=>act({type:'game',action:a})} root/>}
 {b.game?.result&&b.stage==='play'&&<Rewards b={b} names={names} host={isHost||room.hostId===clientId} busy={busy} confirm={()=>run(()=>confirmChallengeRewards(roomCode,clientId,b.id))}/>}
 {['rules','play'].includes(b.stage)&&<p className="bc-board-rule"><strong>Battle rule:</strong> Action Cards and board Mechanic effects do not affect this Battle.</p>}
 {(isHost||room.hostId===clientId)&&<details className="bc-recovery"><summary>Host recovery</summary><p>Cancel for a disconnect or technical problem. No rewards are applied.</p><button disabled={busy} onClick={()=>yes('Cancel this Battle with no reward?')&&run(()=>cancelChallenge(roomCode,clientId,b.id))}>Cancel Battle</button></details>}
 </section>
}
function Teams({g,names}){const hidden=g.engine==='imposter';return <div className="bc-teams">{(hidden?[g.ids]:g.displayTeams||g.sides).map((s,i)=><div key={i}><strong>{hidden?'Players':s.length>1?'Team '+(i+1):'Player'}</strong><p>{s.map(names).join(' + ')}</p></div>)}</div>}
const SPRINT_RULES={'Speed Sprint':'One shot each. Successful goal KPH counts; a miss is 0. Higher wins.','Pinch Sprint':'One legitimate pinch attempt each. Successful goal KPH counts; a miss is 0. Higher wins.','Crossbar Sprint':'Two attempts each. A crossbar hit is 1 point; a miss is 0. Tied players get one extra attempt each.','Freestyle Sprint':'Two attempts each. Judge the best successful shot by difficulty, creativity, execution, and cleanliness. If tied, take one extra attempt each; if everyone misses, repeat.','KPH Guess Sprint':'Head-to-head: take one shot each and guess only the opponent’s shot. FFA: one randomly assigned shared shot; everyone guesses, including the shooter. Lock guesses before revealing goal speed. Lowest error wins.'};
const SPRINT_TEAM_RULES={'Speed Sprint':'Add both teammates’ KPH.','Pinch Sprint':'One team pinch per duo; both players must be involved.','Crossbar Sprint':'Add both teammates’ hits.','Freestyle Sprint':'Two TEAM-PLAY attempts per team; both teammates must be meaningfully involved.','KPH Guess Sprint':'One shooter per team; both opponents guess that shot. Compare combined team error.'};
function Rules({g}){const c=CHALLENGE_BY_ID[g.challengeId],rules=playerRules(g);return <section className="bc-rules"><h3>Rules</h3>{g.sprint?<p>{SPRINT_RULES[g.sprint]} {g.format==='2v2'?SPRINT_TEAM_RULES[g.sprint]:''} Resolve ties before confirming the event. Only tied FFA players repeat; settled placements stay fixed.</p>:<>{rules.setup.length>0&&<p className="bc-setup"><strong>Setup:</strong> {rules.setup.join(' ')}</p>}<ol>{rules.lines.map((line,i)=><li key={i}>{line}</li>)}</ol></>}{g.requirements&&<p><strong>Shot requirements:</strong> {g.requirements.join(' + ')}</p>}</section>}
function Rewards({b,names,host,busy,confirm}){const now=useNow();if(now<b.game.result.revealAt)return <p>Calculating result…</p>;let rank=1;const rewards=rewardDistribution(b);return <div className="bc-results"><h3>Battle results & Token distribution</h3>{b.game.result.placements.map((ids,i)=>{const place=rank;rank+=ids.length;return <p key={i}>#{place} {ids.map(names).join(' / ')} — {ids.map(id=>'+'+rewards[id]+' Tokens').join(' / ')}</p>})}<p>Rewards apply once when the Battle Host continues.</p>{host&&<button disabled={busy} onClick={confirm}>Confirm rewards & Continue</button>}</div>}
export function ChallengeGame({g,uid,host,hostId,names,keys,busy,action,root=false}){const now=useNow(Boolean(g.timer||g.hiddenStartedAt||g.result)),[correction,setCorrection]=useState(false),[privateValue,setPrivate]=useState(null),[unlock,setUnlock]=useState(battleAudioReady());const [lockedPrivate,setLockedPrivate]=useState(null);const lastSound=useRef(''),lastStartSound=useRef(''),lastTurnSound=useRef(''),lastCountdownSound=useRef(''),lastResultSound=useRef('');const [privateError,setPrivateError]=useState('');const packet=g.sealed?.[uid];const n=parseInt(g.challengeId.split('-')[1]),mine=id=>id===uid,alive=g.order.filter(id=>!g.out?.includes(id)),current=alive[g.turn%Math.max(1,alive.length)],inMatch=g.ids.includes(uid);
 useEffect(()=>{let active=true;setPrivate(null);setPrivateError('');if(packet)unseal(uid,packet).then(v=>active&&setPrivate(v)).catch(()=>active&&setPrivateError('Private information could not be opened. Use the original browser, or ask the host to restart this Challenge.'));return()=>{active=false}},[packet?.body,uid]);
 // Reveal only after every required participant committed. Ciphertexts stay unreadable until then.
 useEffect(()=>{let active=true;setLockedPrivate(null);const packet=g.commits?.[uid]?.packet;if(g.engine==='luck'&&packet)unseal(uid,packet).then(v=>active&&setLockedPrivate(v.value)).catch(()=>{});return()=>{active=false}},[g.commits?.[uid]?.hash,uid]);
 useEffect(()=>{if(g.result)stopBattleSpeech();return()=>stopBattleSpeech()},[g.result]);
 const p=SECRET_ENGINES.includes(g.engine)?secretParticipants(g):[];const commit=g.commits?.[uid];const allLocked=p.length>0&&p.every(id=>g.commits?.[id]);
 useEffect(()=>{let cancelled=false;if(commit&&allLocked&&!Object.hasOwn(g.reveals||{},uid)&&!busy)unseal(uid,commit.packet).then(v=>{if(!cancelled)action({type:'reveal',value:v.value,salt:v.salt})}).catch(()=>setPrivateError('Your locked answer could not be opened. Use the original browser, or ask the host to restart.'));return()=>{cancelled=true}},[commit?.hash,allLocked,g.reveals?.[uid],busy]);
 useEffect(()=>{if(!inMatch||busy||g.result||g.tieNotice||g.phase!=='active')return;const timed=(['names','reverseSpeed','gauntlet','timedGoals','hunt','bust'].includes(g.engine)||g.engine==='imposter'&&g.subphase==='discussion')&&g.timer&&!g.timer.pausedAt&&timerLeft(g.timer,now)===0;const bomb=g.engine==='bomb'&&Math.abs(bombPosition(g,now))>=1;if(timed||bomb)action({type:'tick'});if(host&&g.engine==='potato'&&g.hiddenStartedAt&&!g.exploded&&privateValue&&now>=g.hiddenStartedAt+privateValue.duration)action({type:'explode'})},[Math.floor(now/200),g.phase,g.result,busy]);
 const light=g.engine==='light'&&g.timer&&g.phase==='active'?lightAt(g,now):null;const lightMine=light&&inMatch&&(!['1v2','1v3'].includes(g.format)||sideOf(g,uid)===1);
 useEffect(()=>{if((!unlock&&!battleAudioReady())||!inMatch||g.result||g.phase!=='active'||!needsBattleAudio(g))return;const sound=lightMine?'light-'+light.color:g.exploded?'explosion':g.timer&&timerLeft(g.timer,now)===0?'end-'+g.timer.startedAt:'';if(sound&&lastSound.current!==sound){lastSound.current=sound;battleSound(lightMine?light.color:'Explosion').catch(()=>{})}},[light?.color,g.exploded,g.timer&&timerLeft(g.timer,now)===0,unlock]);
 useEffect(()=>{if((!unlock&&!battleAudioReady())||!inMatch||!needsBattleAudio(g)||g.phase!=='active'||g.result)return;const key='start-'+g.instanceId;if(lastStartSound.current!==key){lastStartSound.current=key;battleSound('Start').catch(()=>{})}},[g.phase,g.instanceId,g.result,unlock]);
 useEffect(()=>{if((!unlock&&!battleAudioReady())||!inMatch||g.engine!=='names'||g.phase!=='active'||g.result||!current)return;const key=g.instanceId+'-'+g.turn+'-'+current;if(lastTurnSound.current!==key){lastTurnSound.current=key;battleSound('Turn').catch(()=>{})}},[g.engine,g.phase,g.turn,current,g.result,g.instanceId,unlock]);
 const nameCountdown=g.engine==='names'&&uid===current&&g.timer&&g.phase==='active'&&!g.timer.pausedAt?Math.ceil(timerLeft(g.timer,now)/1000):null;
 useEffect(()=>{if((!unlock&&!battleAudioReady())||!inMatch||uid!==current||nameCountdown==null||nameCountdown<1||nameCountdown>3||now<g.timer.startedAt)return;const key=g.timer.startedAt+'-'+nameCountdown;if(lastCountdownSound.current!==key){lastCountdownSound.current=key;battleSound('Tick').catch(()=>{})}},[nameCountdown,g.timer?.startedAt,unlock]);
 useEffect(()=>{if((!unlock&&!battleAudioReady())||!inMatch||!g.result||now<g.result.revealAt)return;const key=g.instanceId+'-'+g.result.revealAt;if(lastResultSound.current!==key){lastResultSound.current=key;battleSound('Success').catch(()=>{})}},[g.result?.revealAt,g.instanceId,now,unlock]);
 useEffect(()=>{if((!unlock&&!battleAudioReady())||!inMatch||g.phase!=='active'||g.result||!['bomb','potato'].includes(g.engine)||g.engine==='bomb'&&g.timer?.pausedAt||g.engine==='potato'&&(!g.hiddenStartedAt||g.exploded))return;const interval=setInterval(()=>battleSound('Tick').catch(()=>{}),1000);return()=>clearInterval(interval)},[g.engine,g.phase,g.result,g.timer?.pausedAt,g.hiddenStartedAt,g.exploded,unlock]);
 const send=a=>!busy&&action(a);const btn=(label,a,enabled=host)=>enabled&&<button type="button" disabled={busy} onClick={()=>a.type==='reroll'?(yes('All players agreed to abandon this selection and reroll?')&&send(a)):send(a)}>{label}</button>;
 const submit=async value=>{if(!keys[uid])return;const c=await commitment(uid,value,keys[uid]);send({type:'commit',commit:c})};
 if(g.phase==='ready')return <div className="bc-match"><Teams g={g} names={names}/><BattleTurnOrder g={g} names={names}/><Rules g={g}/>{g.engine==='gauntlet'&&<Scoreboard g={g} names={names}/>}
 {needsBattleAudio(g)&&<BattleAudioCheck onReady={()=>setUnlock(true)}/>}{btn('Agreed setting reroll',{type:'reroll',confirmed:true},host&&g.engine==='mode')}{btn('Start this match',{type:'start'})}</div>;
 if(g.result&&!correction)return <div className="bc-match"><h3>{g.sprint||CHALLENGE_BY_ID[g.challengeId].name}</h3>{now<g.result.revealAt?<p>Result incoming…</p>:g.result.placements.map((ids,i)=><p key={i}>{i===0?'Leading: ':''}{ids.map(names).join(' + ')}</p>)}{host&&<button onClick={()=>setCorrection(true)}>Correct result</button>}{btn('Undo last input',{type:'undo'},host&&!!g.history?.length)}{host&&g.matches&&Object.entries(g.matches).filter(([,m])=>m.result).map(([id])=><button key={id} onClick={()=>send({type:'reopenMatch',matchId:id})}>Reopen {id}</button>)}</div>;
 if(correction)return <div className="bc-match"><h3>Correct result</h3><p>This preserves teams and random selections.</p><Placement g={g} names={names} allowDraw override onSubmit={(placements)=>{send({type:'manualResult',placements,override:true});setCorrection(false)}}/>{btn('Undo last input',{type:'undo'},host&&!!g.history?.length)}<button onClick={()=>setCorrection(false)}>Back</button></div>;
 if(g.tieNotice)return <div className="bc-match bc-tie" role="alert"><h2>Tie — another round!</h2><p>{g.tieNotice.message}</p><Scoreboard g={g} names={names}/><Rules g={g}/>{btn('Continue to tiebreak',{type:'continueTie'})}{!host&&<p>Waiting for the host to continue…</p>}</div>;
 if(g.phase==='round-summary')return <div className="bc-match"><h2>{names(g.roundWinner)} wins this round</h2><Scoreboard g={g} names={names}/>{btn('Next round',{type:'nextClosestRound'})}</div>;
 if(g.phase==='tiebreak')return <div className="bc-match"><h2>Tie — tiebreak required</h2><Scoreboard g={g} names={names}/><Rules g={g}/><p>{(g.tieGroups||[]).map(ids=>ids.map(names).join(' / ')).join(' · ')} take the next tiebreak attempt. Other placements stay fixed.</p>{btn('Start tiebreak',{type:'tiebreak'})}</div>;
 return <div className={'bc-match '+(lightMine?'bc-light-'+light.color:'')}>
 {privateError&&<p role="alert">{privateError}</p>}{lightMine&&<div aria-hidden="true" className={'bc-signal bc-signal-'+light.color}/>}<h3>{g.sprint||CHALLENGE_BY_ID[g.challengeId].name}</h3><Teams g={g} names={names}/><BattleTurnOrder g={g} names={names}/><Rules g={g}/>{g.engine!=='gauntlet'&&<Scoreboard g={g} names={names}/>}
 <p>Round {g.round||1}{g.level?' · Level '+g.level:''}</p>{g.setting&&<h3>{g.setting}</h3>}{g.mechanic&&<h3>{g.mechanic.name} · {g.mechanic.difficulty}</h3>}{g.draft&&<div className="bc-grid">{g.draft.map((m,i)=><div key={i}>{m.difficulty}: {m.name}<small>{g.engine==='draft'?i+1+' mini-points':''}</small></div>)}</div>}
 {g.timer&&g.engine!=='light'&&g.engine!=='bomb'&&<output className="bc-timer" aria-label={g.engine==='names'?names(current)+' — time remaining':'Time remaining'}>{g.engine==='names'&&<span>{names(current)} · </span>}{g.timer.duration==null?fmt(timerElapsed(g.timer,now)):fmt(timerLeft(g.timer,now))}{g.timer.pausedAt?' · Paused':''}{now<g.timer.startedAt?' · Get ready':''}</output>}
 {g.engine==='gauntlet'&&<Scoreboard g={g} names={names}/>}
 {needsBattleAudio(g)&&<BattleAudioCheck onReady={()=>setUnlock(true)}/>}
 {lightMine&&<h2>{light.color.toUpperCase()}</h2>}{light&&!lightMine&&inMatch&&<p>You are unrestricted.</p>}
 {g.engine==='manual'&&[74,75].includes(n)&&btn('Draw next mechanic',{type:'reroll',confirmed:true})}
 {['manual','sprintJudge'].includes(g.engine)&&host&&<Placement g={g} names={names} allowDraw={drawAllowed(g)} onSubmit={placements=>send({type:'manualResult',placements})}/>}
 {['mechanic','mode','arena','light'].includes(g.engine)&&<>{btn('Agreed reroll',{type:'reroll',confirmed:true},host&&['mechanic','draft'].includes(g.engine))}{host&&<Placement g={g} names={names} onSubmit={placements=>send({type:'manualResult',placements})}/>}</>}
 {['manual','mechanic','mode','arena','light','sprintJudge'].includes(g.engine)&&!drawAllowed(g)&&btn('Scores tied — show tiebreak rules',{type:'announceTie'})}
 {g.engine==='draft'&&<DraftControls g={g} uid={uid} names={names} busy={busy} send={send}/>}
 {g.engine==='possession'&&<PossessionControls g={g} uid={uid} names={names} busy={busy} now={now} send={send}/>}
 {['tournament','potatoTournament'].includes(g.engine)&&<>
 {!host&&<p className="bc-private-note">Only your current tournament matchup is shown on this device. The Battle Host can see both simultaneous matches.</p>}
 {g.stage==='placementChoice'&&<><p>Final and third-place match are ready.</p>{['both','final','third'].map(mode=><span key={mode}>{btn(mode==='both'?'Play simultaneously':mode+' first',{type:'placementMode',mode})}</span>)}</>}
 <div className="bc-grid">{Object.entries(g.matches||{}).filter(([id,m])=>(g.stage==='opening'?id==='opening':g.stage==='semis'?['a','b'].includes(id):['final','third'].includes(id))&&(host||m.ids?.includes(uid))).map(([id,m])=>{const waiting=g.stage==='placementChoice'||g.stage==='placements'&&g.playMode!=='both'&&id!==g.playMode&&!g.matches[g.playMode]?.result;return <section key={id}><h3>{id==='opening'?'Opening 2v2':id==='a'?'Semifinal A':id==='b'?'Semifinal B':id==='third'?'Third place':'Final'}</h3>{waiting?<p>Waiting / Up next — {m.ids.map(names).join(' vs ')}</p>:<ChallengeGame g={m} uid={uid} host={host} hostId={hostId} names={names} keys={keys} busy={busy} action={a=>send({type:'matchAction',matchId:id,action:a})}/>}</section>})}</div></>}
 {g.engine==='sprintScore'&&(['1v1v1','1v1v1v1'].includes(g.format)?g.tieGroups?.flat()||g.sprintSubmitters:g.sprintSubmitters).map(id=><div key={id}><strong>{names(id)}{g.format==='2v2'&&g.sprint==='Pinch Sprint'?' (team pinch)':''}</strong><p>Attempts: {(g.entries?.[id]||[]).join(', ')||'None'}</p>{mine(id)&&((g.entries?.[id]?.length||0)<(g.tieGroups?1:g.sprintAttempts))&&(g.sprint==='Crossbar Sprint'?<>{btn('Hit',{type:'attempt',playerId:id,value:1},true)}{btn('Miss',{type:'attempt',playerId:id,value:0},true)}</>:<Num label="Goal KPH (0 = miss)" disabled={busy} onSubmit={value=>send({type:'attempt',playerId:id,value})}/>)}</div>)}
 {g.engine==='numeric'&&!(n===11&&g.format==='1v1')&&<><h3>{g.target?'Target: '+g.target+' KPH':'Enter attempts'}</h3>{g.ids.filter(id=>!g.tieGroups||g.tieGroups.flat().includes(id)).filter(id=>![61,62].includes(n)||g.sides.some(s=>s[0]===id)).map(id=><div key={id}><strong>{names(id)}</strong><p>{(g.entries?.[id]||[]).join(' + ')||'No attempts yet'} · Total: {(g.entries?.[id]||[]).reduce((a,b)=>a+b,0)}</p>{mine(id)&&(g.entries?.[id]?.length||0)<(g.tieGroups||[55,65].includes(n)?1:3)&&<Num label={n===65?'Goals':n===55?'Goal KPH':'KPH (0 = miss)'} integer={n===65} disabled={busy} onSubmit={value=>send({type:'attempt',playerId:id,value})}/>}</div>)}</>}
 {g.engine==='numeric'&&n===11&&g.format==='1v1'&&<>{g.ids.map(id=><div key={id}>{names(id)} {g.kuxir?.[id]===undefined?<>{btn('Scored',{type:'scored',playerId:id},mine(id))}{btn('Missed',{type:'missed',playerId:id},mine(id))}</>:g.kuxir[id]?'Scored':'Missed'}{g.kuxir?.[id]&&g.ids.every(x=>g.kuxir?.[x])&&mine(id)&&<Num label="Kuxir goal KPH" onSubmit={value=>send({type:'kph',playerId:id,value})}/>}</div>)}</>}
 {g.engine==='ladder'&&g.ids.map(id=><div key={id}><strong>{names(id)}</strong><p>Completed {g.ladders[id].level} · Misses {g.ladders[id].misses}/{n===12?3:2} {g.ladders[id].done?'— Finished':''}</p>{!g.ladders[id].done&&<>{btn('Made',{type:'made',playerId:id},mine(id))}{btn('Missed',{type:'miss',playerId:id},mine(id))}</>}</div>)}
 {g.engine==='reset2'&&alive.map(id=><div key={id}>{names(id)} — {g.roundInputs?.[id]===undefined?'Waiting':g.roundInputs[id]?'Made':'Missed'}{g.roundInputs?.[id]===undefined&&<>{btn('Made',{type:'made',playerId:id},mine(id))}{btn('Missed',{type:'miss',playerId:id},mine(id))}</>}</div>)}
 {['horse','chain','copySurvival'].includes(g.engine)&&<><p>Phase: {g.subphase} · {g.engine==='copySurvival'?'Survived '+g.survived:current?.startsWith('team')?g.sides[Number(current.at(-1))].map(names).join(' + '):names(current)}</p>{g.lives&&<p>{Object.entries(g.lives).map(([id,l])=>(id.startsWith('team')?id:names(id))+': '+l+' remaining').join(' · ')}</p>}{g.subphase==='copy'&&g.engine!=='chain'?(g.engine==='copySurvival'?g.sides[1]:g.required||[]).map(id=><div key={id}>{names(id)}{g.copies?.[id]===undefined?<>{btn('Copied',{type:'made',playerId:id})}{btn('Failed copy',{type:'miss',playerId:id})}</>:g.copies[id]?'Made':'Missed'}</div>):<>{btn('Made',{type:'made'})}{btn('Missed',{type:'miss'})}</>}</>}
 {g.engine==='survival'&&g.ids.map(id=><div key={id}>{names(id)}: {g.out?.includes(id)?'Eliminated':'Still playing'} {btn('I am eliminated',{type:'life',playerId:id},mine(id)&&!g.out?.includes(id))}</div>)}
 
 {g.engine==='ttt'&&<><p>{g.order.map(id=>names(id)+' = '+g.marks[id]).join(' · ')} · {n===52?'Turn: '+names(g.order[g.turn%2]):'Take turns verbally; only claim successful mechanics.'}</p><div className="bc-ttt">{Array.from({length:9},(_,i)=><button key={i} disabled={busy||!inMatch||n===52&&(!!g.tiles?.[i]||uid!==g.order[g.turn%2])||n===28&&g.tiles?.[i]&&g.tiles[i]!==uid} onClick={()=>{if(n===52||yes(g.tiles?.[i]?'Remove your mistaken marker?':'Did you successfully complete '+g.tileMechanics[i].name+'?'))send({type:'claim',tile:i})}}>{g.tiles?.[i]?g.marks[g.tiles[i]]:n===28?g.tileMechanics[i].name:'·'}</button>)}</div>{n===28&&host&&<select defaultValue="" onChange={e=>{if(e.target.value!==''&&yes('Both players agreed to reroll this unclaimed tile?'))send({type:'rerollTile',tile:Number(e.target.value)});e.target.value=''}}><option value="">Reroll unclaimed tile…</option>{Array.from({length:9},(_,i)=>!g.tiles?.[i]&&<option key={i} value={i}>Tile {i+1}</option>)}</select>}</>}
 {g.engine==='ttt'&&n===28&&btn('Agreed draw',{type:'manualResult',placements:[g.ids],override:true})}
 {g.engine==='tug'&&<><div className="bc-rope-names">{g.sides.map((side,i)=><strong key={i} style={{color:i?'#60a5fa':'#fb7185'}}>{side.map(names).join(' + ')}</strong>)}</div><div className="bc-track"><span className="bc-rope-marker" style={{left:(g.rope+g.limit)/(2*g.limit)*100+'%'}}>●</span></div><p>Win endpoints: {g.limit} pulls from center</p>{inMatch&&<div><strong>Your mechanic: {g.mechanics[uid].name}</strong>{btn('Completed',{type:'complete',revision:g.mechanicVersions?.[uid]||0},true)}{btn('Reroll (1-space penalty)',{type:'rerollOwn',revision:g.mechanicVersions?.[uid]||0},true)}</div>}</>}
 {g.engine==='bomb'&&<><div className="bc-track"><span style={{left:(bombPosition(g,now)+1)*50+'%'}}>💣</span></div><p>Bomb moving toward {g.sides[g.bomb.direction<0?0:1].map(names).join(' + ')}</p>{btn('Valid unused answer — Reverse bomb',{type:'reverse',revision:g.bomb.version},inMatch&&sideOf(g,uid)===(g.bomb.direction<0?0:1))}</>}
 {g.engine==='alphabet'&&<><h2>{g.letter||'Ready for a letter?'}</h2>{!g.letter&&btn('Choose letter',{type:'chooseLetter'})}{g.ids.map(id=><div key={id}>{names(id)}: {g.scores[id]} {btn('+1 successful mechanic',{type:'point',playerId:id},mine(id)&&!!g.letter)}</div>)}</>}
 {g.engine==='bust'&&<section className="bc-bust"><p className="bc-eyebrow">KPH Bust · Round {g.round}</p><h2>{Math.max(0,Number(g.bustRemaining)||0)} KPH remaining</h2><p>Fresh target: {g.bustTarget} KPH · Turn: <strong>{names(current)}</strong></p>{g.timer&&<p className="bc-bust-timer">{now<g.timer.startedAt?'Get ready…':`⏱ ${Math.ceil(timerLeft(g.timer,now)/1000)}s`}</p>}{mine(current)&&now>=g.timer?.startedAt&&<Num label="Scored goal KPH" integer disabled={busy} onSubmit={value=>send({type:'bustKph',value})}/>}<p><strong>Out:</strong> {(g.out||[]).map(names).join(', ')||'Nobody'}</p>{(g.bustHistory||[]).length>0&&<div className="bc-bust-history">{g.bustHistory.slice(-4).reverse().map((entry,i)=><small key={`${entry.round}-${entry.playerId}-${i}`}>{names(entry.playerId)}: {entry.before} − {entry.value} = {entry.after}{entry.after<0?' · BUST':''}</small>)}</div>}</section>}
 {g.engine==='names'&&<><h3>{names(current)} — Name a {n===47?'car':'pro / creator'}</h3>{btn('I said an unused answer',{type:'pass'},inMatch&&uid===current)}{inMatch&&uid!==current&&<p>Waiting for {names(current)} to answer…</p>}<p>A repeated or invalid name does not count. Say a different valid name before your time runs out.</p>{g.redoNotice&&<p role="status">Redo: {names(g.redoNotice.playerId)} has {fmt(g.redoNotice.remainingMs)} remaining.</p>}{host&&g.lastPass&&<button type="button" disabled={busy} onClick={()=>yes('Return only '+names(g.lastPass.playerId)+' to their previous turn with '+fmt(g.lastPass.remainingMs)+' remaining?')&&send({type:'redoLastPass'})}>Redo last player’s turn</button>}</>}
 {g.engine==='speedladder'&&<><p>{names(current)}: {g.subphase==='set'?'Set a fresh baseline':'Beat the baseline'}</p>{g.subphase==='set'?btn('Baseline set',{type:'baseline'},mine(current)):<>{btn('Higher',{type:'higher'},mine(current))}{btn('Failed',{type:'failed'},mine(current))}</>}<p>{g.ids.map(id=>names(id)+': '+g.lives[id]+' hearts').join(' · ')}</p></>}
 {['reverseSpeed','sprint','airdribble','gauntlet'].includes(g.engine)&&<><p>Current player: {names(current)} {g.baseline!=null?' · Baseline: '+g.baseline+' KPH':''}</p>
 {g.engine==='sprint'&&!['1v2','1v3'].includes(g.format)?g.ids.map(id=><div key={id}>{names(id)}{g.entries?.[id]?' — Finish submitted':btn('Finished shot #10',{type:'finish',playerId:id},mine(id))}</div>):<>
 {!g.timer&&btn('Start run',{type:'timerStart'},g.engine==='airdribble'?inMatch&&uid!==current:mine(current))}
 {g.timer&&!g.timer.pausedAt&&g.engine!=='gauntlet'&&btn(g.engine==='reverseSpeed'?'Goal scored — Stop timer':'Stop timer',{type:'timerStop'},g.engine==='airdribble'?mine(g.operator):mine(current))}
 {g.engine==='gauntlet'&&g.timer&&btn('Complete '+['Easy','Medium','Hard'][g.laps?.[current]?.length||0],{type:'complete'},mine(current))}
 {g.timer?.pausedAt&&(g.engine==='reverseSpeed'?mine(current)&&<Num label="Actual goal KPH" disabled={busy} onSubmit={value=>send({type:'kph',value})}/>:<>{btn('Valid goal / Submit time',{type:'submitRun'},g.engine==='airdribble'?mine(g.operator):mine(current))}</>)}
 {btn('Redo current run',{type:'redoRun'},g.engine==='airdribble'?mine(g.operator):mine(current))}</>}</>}
 {g.engine==='endurance'&&<>{!g.timer&&btn('Start '+names(current)+' run',{type:'timerStart'},mine(current))}{g.timer&&timerLeft(g.timer,now)===0&&g.ids.filter(id=>!['1v2','1v3'].includes(g.format)||id===current).map(id=><div key={id}>{names(id)}: {g.entries?.[id]??'Waiting'}{mine(id)&&g.entries?.[id]===undefined&&<Num label="Shot number you ended at" integer disabled={busy} onSubmit={value=>send({type:'count',playerId:id,value})}/>}</div>)}</>}
 {g.engine==='series'&&!g.matches?.current&&<><p>{(g.overtime?g.tiebreakPair:g.pairs[g.segment])?.map(names).join(' vs ')}</p><p>{g.overtime?'Next qualifying score wins':'Segment '+(g.segment+1)+' / '+g.pairs.length} · Totals: {(g.totals||[0,0]).join(' – ')}</p>{(g.overtime||g.seriesMode==='wins')?host&&<>{btn('Solo / Team A won',{type:'segment',side:0})}{btn('Team member / Team B won',{type:'segment',side:1})}</>:g.pairs[g.segment]?.includes(uid)&&g.seriesInputs?.[uid]===undefined&&<Num label="Your goals this segment" integer disabled={busy} onSubmit={value=>send({type:'segment',value})}/>}</>}
 {g.engine==='series'&&g.matches?.current&&<><p>Mini-match {g.segment+1} · Side score {(g.totals||[0,0]).join(' – ')}</p><ChallengeGame g={g.matches.current} uid={uid} host={host} hostId={hostId} names={names} keys={keys} busy={busy} action={a=>send({type:'matchAction',matchId:'current',action:a})}/>{g.matches.current.result&&btn('Continue series',{type:'nextSegment'})}</>}
 {g.engine==='triathlon'&&<><p>Event {g.eventIndex+1}: {g.events[g.eventIndex]}</p><p>{g.events.join(' → ')}</p><p>{g.ids.map(id=>names(id)+': '+g.scores[id]).join(' · ')}</p><ChallengeGame g={g.matches.current} uid={uid} host={host} hostId={hostId} names={names} keys={keys} busy={busy} action={a=>send({type:'matchAction',matchId:'current',action:a})}/>{g.matches.current.result&&btn('Confirm event result & Continue',{type:'nextEvent'})}</>}
 {g.engine==='kickoff'&&<><p>{g.pairs[g.pairIndex]?.map(names).join(' vs ')} · Kickoff {g.kickoffCount+1}/{g.kickoffLimit}</p>{g.pairs[g.pairIndex]?.map(id=><span key={id}>{btn(names(id)+' won kickoff',{type:'kickoff',playerId:id})}</span>)}</>}
 {['goals','timedGoals'].includes(g.engine)&&<><p>{g.sides.map((s,i)=>s.map(names).join(' + ')+': '+s.reduce((t,id)=>t+(g.scores[id]||0),0)).join(' · ')}</p>{g.phase==='overtime'&&<h3>Next qualifying score wins</h3>}{g.sides.map((s,i)=>((![66,76].includes(n)||i===1)&&(![67,77].includes(n)||i===0))&&<span key={i}>{btn(n===83&&i===0?'Solo hit back wall':s.map(names).join(' + ')+' scored',{type:'goal',side:i},g.sides[i].includes(uid))}</span>)}</>}
 {g.engine==='hunt'&&<><h3>{n===71&&g.subphase==='headstart'?'Runner head start — Hunters wait':'Hunt active'}</h3>{n===71?btn('Runner demoed',{type:'demo'},uid===g.sides[0][0]&&g.subphase==='hunt'):g.sides[1].filter(id=>!g.out?.includes(id)).map(id=><span key={id}>{btn(names(id)+' demoed',{type:'demo',playerId:id},uid===id)}</span>)}</>}
 {g.engine==='pressure'&&<>{g.normalAttacksDone&&host&&<><p>Normal possessions complete. If tied, use paired pressure attempts before selecting a winner.</p><Placement g={g} names={names} onSubmit={placements=>send({type:'manualResult',placements})}/></>}<p>Attacking: {g.sides[g.turn%2].map(names).join(' + ')}</p>{[15,10,5].map(seconds=><span key={seconds}>{btn('Start '+seconds+'s',{type:'timerStart',seconds},host||g.sides[g.turn%2].includes(uid))}</span>)}{(host||g.sides[g.turn%2].includes(uid))&&<button onClick={()=>yes('Have you completed all three time limits?')&&send({type:'endTurn',confirmed:true})}>End attacking turn</button>}</>}
 {g.engine==='heads'&&g.sides.map((s,i)=><div key={i}>{s.map(names).join(' + ')}{btn('Side succeeded',{type:'sideResult',side:i,made:true})}{btn('Side failed',{type:'sideResult',side:i,made:false})}</div>)}
 {g.engine==='combo'&&g.ids.map(id=><div key={id}><h4>{names(id)}</h4>{g.combo[sideOf(g,id)].map((m,i)=><p key={i}>{m.name} {Object.hasOwn(g.comboInputs||{},id+'_'+i)?g.comboInputs[id+'_'+i]?'Made':'Missed':<>{btn('Made first try',{type:'combo',playerId:id,index:i,made:true},mine(id))}{btn('Missed',{type:'combo',playerId:id,index:i,made:false},mine(id))}</>}</p>)}</div>)}
 {g.engine==='relay'&&<><p>Solo: One-bounce Kuxir. Trio: Easy → Medium → Hard.</p>{btn('Solo completed',{type:'complete'},uid===g.sides[0][0])}{g.sides[1].map((id,i)=><p key={id}>{names(id)} — {g.draft[i].name} {i<g.turn?'Done':i===g.turn?btn('Completed relay mechanic',{type:'complete'},uid===id):'Waiting'}</p>)}</>}
 {g.engine==='shark'&&<><h3>Crossing {g.crossing}/{g.crossings} · {g.crossing%2?'Blue → Orange':'Orange → Blue'}</h3>{g.phase==='regroup'?<>{btn('Regrouped — Start next crossing',{type:'nextCrossing'})}</>:g.sides[1].map(id=><p key={id}>{names(id)}: {g.out?.includes(id)?'Out':g.safe?.[id]?'Safe':<>{btn('Reached safety',{type:'safe',playerId:id},mine(id))}{btn('Demoed',{type:'eliminate',playerId:id},mine(id))}</>}</p>)}</>}
 {SECRET_ENGINES.includes(g.engine)&&<SecretControls g={g} uid={uid} host={host} hostId={hostId} names={names} busy={busy} privateValue={privateValue} lockedPrivate={lockedPrivate} send={send} submit={submit} now={now}/>}
 {host&&<details className="bc-recovery"><summary>Match recovery</summary>{g.matches&&Object.entries(g.matches).filter(([,m])=>m.result).map(([id])=><button key={id} onClick={()=>yes('Reopen '+id+'? Later match progress may need replaying; game selections stay fixed.')&&send({type:'reopenMatch',matchId:id})}>Reopen {id}</button>)}{btn('Undo last input',{type:'undo'},!!g.history?.length)}{g.timer&&<>{g.timer.pausedAt?btn('Resume play',{type:'resume'}):btn('Pause for setup / dispute',{type:'pause'})}</>}<button disabled={busy} onClick={()=>yes('Restart this Challenge? Its progress and random choices will reset.')&&send({type:'restart',confirmed:true})}>Restart Challenge</button><button onClick={()=>setCorrection(true)}>Correct / manually resolve result</button></details>}
 </div>
}
function PairScores({onSubmit,busy}){const [left,setLeft]=useState(''),[right,setRight]=useState('');return <form onSubmit={e=>{e.preventDefault();if(left!==''&&right!=='')onSubmit(Number(left),Number(right))}}><label>Solo / Team A goals<input required min="0" step="1" type="number" value={left} onChange={e=>setLeft(e.target.value)}/></label><label>Opponent / Team B goals<input required min="0" step="1" type="number" value={right} onChange={e=>setRight(e.target.value)}/></label><button disabled={busy||left===''||right===''}>Submit segment scores</button></form>}
function SecretControls({g,uid,host,hostId,names,busy,privateValue,lockedPrivate,send,submit,now}){const n=parseInt(g.challengeId.split('-')[1]),p=secretParticipants(g),locked=!!g.commits?.[uid],[choice,setChoice]=useState('');const btn=(label,a,enabled=host)=>enabled&&<button disabled={busy} onClick={()=>a.type==='reroll'?(yes('All players agreed to abandon this selection and reroll?')&&send(a)):send(a)}>{label}</button>;const needDeal=['target','boss','luck','imposter','potato'].includes(g.engine)&&!Object.keys(g.sealed||{}).length;
 return <div className="bc-secret">{needDeal?<>{btn('Deal private information',{type:'deal'})}{!host&&<p>Waiting for the Battle Host to deal…</p>}</>:<>
 {g.engine==='luck'&&<>{privateValue&&!locked&&<div className="bc-private"><h3>Your secret number: {privateValue.first}</h3><button disabled={busy} onClick={()=>submit(privateValue.first)}>Bank</button><button disabled={busy} onClick={()=>submit(privateValue.second)}>Risk — discard this and keep one new number</button></div>}{locked&&<p>Your locked number: <strong>{lockedPrivate??'Opening…'}</strong>. Only you can see this until everyone is ready.</p>}{g.ids.every(id=>Object.hasOwn(g.reveals||{},id))&&btn('Reveal results',{type:'luckReveal'})}</>}
 {g.engine==='auction'&&<><p>Round {g.round}/3 · First success gets 1 mini-point and ends the round.</p>{g.subphase==='bid'&&!Object.keys(g.commits||{}).length&&btn('Draw another Hard mechanic',{type:'rerollHard'})}{g.subphase==='bid'&&p.includes(uid)&&!locked&&<select value="" onChange={e=>e.target.value&&submit(Number(e.target.value))}><option value="">Secret bid…</option>{[1,2,3,4,5].map(v=><option key={v}>{v}</option>)}</select>}{g.subphase==='attempt'&&<><p>{names(g.bidOrder[g.bidIndex])}: up to {g.reveals[g.bidOrder[g.bidIndex]]} attempts.</p>{btn('Succeeded',{type:'auctionAttempt',made:true},uid===g.bidOrder[g.bidIndex])}{btn('Failed all bid attempts',{type:'auctionAttempt',made:false},uid===g.bidOrder[g.bidIndex])}</>}{g.subphase==='roundResult'&&btn('Continue',{type:'nextRound'})}</>}
 {g.engine==='guess'&&<><p>Shooter: {names(g.shooters[g.shot])} · Shot {g.shot+1}/{g.shooters.length}. Pause Rocket League before the replay reveals speed.</p>{n===39&&g.estimate===undefined&&uid===g.shooters[g.shot]&&<Num label="Shooter's announced estimate" onSubmit={value=>send({type:'estimate',value})}/>} {g.estimate!==undefined&&<p>Estimate: {g.estimate} KPH</p>}{g.subphase==='guess'&&p.includes(uid)&&!locked&&(n===39?g.estimate!==undefined&&<><button onClick={()=>submit('higher')}>Higher</button><button onClick={()=>submit('lower')}>Lower</button></>:<Num label="Your secret KPH guess" onSubmit={submit} disabled={busy}/>)}{g.subphase==='actual'&&uid===g.shooters[g.shot]&&<Num label="Actual Rocket League KPH" onSubmit={value=>send({type:'actual',value})} disabled={busy}/>} {g.subphase==='shotResult'&&<><p>Actual: {g.actual} KPH</p>{uid===g.shooters[g.shot]&&<details><summary>Correct actual KPH (guesses stay locked)</summary><Num label="Correct actual KPH" onSubmit={value=>send({type:'actual',value})}/></details>}{Object.entries(g.scores).map(([id,s])=><p key={id}>{names(id)}: {s} {n===30?'total error':'points'}</p>)}{btn('Continue',{type:'nextShot'})}</>}</>}
 {g.engine==='target'&&<><h3>{g.shot>=6?'Tiebreak '+(Math.floor((g.shot-6)/2)+1):'Round '+(Math.floor(g.shot/3)+1)} · Attacking: {g.sides[g.turn%2].map(names).join(' + ')}</h3><p>Possession {g.shot<6?g.shot%3+1:(g.shot-6)%2+1} / {g.shot<6?3:2} · {g.subphase==='attack'?'Play the attack and report its result':g.subphase==='predict'?'Defender: lock your prediction':g.subphase==='revealTarget'?'Attacker: reveal the target':'Possession complete'}</p>{privateValue?.target&&g.sides[g.turn%2].includes(uid)&&<div className="bc-private">Your secret target: <strong>{privateValue.target}</strong>. Do not show defenders.</div>}{g.subphase==='attack'&&g.sides[g.turn%2].includes(uid)&&[2,1,0].map(v=><button key={v} disabled={busy} onClick={()=>yes('Submit '+v+' attacking points?')&&send({type:'attackResult',value:v})}>{v===2?'Scored + hit target':v===1?'Scored + missed target':'Missed / Saved'}</button>)}{g.subphase==='predict'&&p.includes(uid)&&!locked&&<select value="" onChange={e=>e.target.value&&yes('Lock prediction: '+e.target.value+'?')&&submit(e.target.value)}><option value="">Predict secret target…</option>{TARGETS.map(t=><option key={t}>{t}</option>)}</select>}{g.subphase==='revealTarget'&&privateValue?.target&&g.sides[g.turn%2].includes(uid)&&btn('Reveal locked target',{type:'targetReveal',target:privateValue.target},true)}{g.subphase==='shotResult'&&<><p>Target: {g.target} · Prediction: {Object.values(g.reveals||{}).join(', ')}</p><p role="status">{Object.values(g.reveals||{}).includes(g.target)?'Correct prediction! Defenders earn +1 point!':'The prediction missed — no defending point.'} Attackers earned +{g.attackScore} points.</p><p>{g.sides.map(s=>s.map(names).join(' + ')+': '+g.scores[s[0]]).join(' · ')}</p>{btn('Next possession',{type:'nextShot'})}</>}</>}
 {g.engine==='boss'&&<><p>Round {g.round}/{g.totalRounds}. Boss: {names(g.sides[0][0])}</p>{g.subphase==='bossChoose'&&privateValue?.options&&uid===g.sides[0][0]&&privateValue.options.map(m=><button key={m.id} disabled={busy} onClick={()=>yes('Choose '+m.name+'?')&&send({type:'bossChoose',value:m.id})}>{m.name}</button>)}{g.subphase==='challenger'&&(host||g.sides[1].includes(uid))&&g.sides[1].filter(id=>!g.out?.includes(id)).map((id,_,alive)=><button key={id} disabled={busy||alive.length>1&&g.lastChallenger===id} onClick={()=>send({type:'challenger',playerId:id})}>Choose {names(id)}</button>)}{g.subphase==='attempt'&&<><p>{names(g.challenger)} · Attempt {g.attempt}/2</p>{btn('Made',{type:'bossAttempt',made:true},uid===g.challenger)}{btn('Missed',{type:'bossAttempt',made:false},uid===g.challenger)}</>}{g.subphase==='roundResult'&&btn('Next round',{type:'nextRound'})}<p>Out: {(g.out||[]).map(names).join(', ')||'Nobody'}</p></>}
 {g.engine==='imposter'&&<>{privateValue&&<details className="bc-private"><summary>Show my private role</summary><strong>{privateValue.role==='imposter'?'IMPOSTER — blend in':'NON-IMPOSTER'}</strong>{privateValue.prompt&&<p>Secret prompt: {privateValue.prompt.name}</p>}</details>}{g.subphase==='roles'&&btn('Everyone checked roles — Start free clue phase',{type:'rolesReady'})}{g.subphase==='freeClues'&&<><h3>{g.round>1?'Extra clue round':'Free clue phase'}</h3><p>{n===80?'Take your shot clues naturally. The browser is not enforcing a turn order.':'Give one verbal clue each naturally. The browser is not enforcing a turn order.'}</p><p>When everyone is done, the Host starts the shared discussion timer.</p>{btn('Ready for discussion — Start 2:00',{type:'startDiscussion'})}{btn('Ready to vote now',{type:'voteStart'})}</>}{g.subphase==='discussion'&&<><h3>Discussion</h3><div className="bc-discussion-clock">{Math.floor(Math.ceil(timerLeft(g.timer,now)/1000)/60)}:{String(Math.ceil(timerLeft(g.timer,now)/1000)%60).padStart(2,'0')}</div><p>Discuss the clues, accuse, defend and bluff. Voting opens automatically at 0:00.</p>{btn('End discussion early & Vote',{type:'voteStart'})}</>}{g.subphase==='vote'&&!locked&&<select value="" onChange={e=>e.target.value&&yes('Lock your vote?')&&submit(e.target.value)}><option value="">Vote for another player…</option>{g.ids.filter(id=>id!==uid).map(id=><option key={id} value={id}>{names(id)}</option>)}</select>}{g.subphase==='accused'&&<><p>Accused: {names(g.accused)}</p>{uid===g.accused&&privateValue&&btn('Reveal my role',{type:'accusedRole',imposter:privateValue.role==='imposter'},true)}</>}{g.subphase==='identify'&&privateValue?.role==='imposter'&&btn('Reveal that I was the Imposter',{type:'identify',imposter:true},true)}{g.subphase==='finalGuess'&&uid===g.imposter&&<><p>One exact prompt guess to steal the win.</p><input placeholder="Filter answers…" value={choice} onChange={e=>setChoice(e.target.value)}/><select value="" onChange={e=>e.target.value&&yes('Submit your ONE final guess?')&&send({type:'finalGuess',value:e.target.value})}><option value="">Choose your final answer…</option>{(n===81?WORDS:[...PARTY_MECHANICS,...REQUIREMENTS.map(name=>({id:name,name})),...['slow','medium','fast'].map(speed=>({id:'speed-'+speed,name:speed[0].toUpperCase()+speed.slice(1)+' shot'}))]).filter(v=>v.name.toLowerCase().includes(choice.toLowerCase())).map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></>}{g.subphase==='verify'&&privateValue?.prompt&&btn('Reveal prompt and resolve guess',{type:'verify',prompt:privateValue.prompt},true)}</>}
 {g.engine==='potato'&&<><strong>SKIP ALL REPLAYS IMMEDIATELY.</strong>{!g.hiddenStartedAt?btn('Start Hot Potato',{type:'bombStart'}):g.exploded?<><h2>💥 EXPLOSION</h2><p>If ball was at center: play the kickoff and use the half it enters. No timer restart for this.</p>{g.sides.map((s,i)=><span key={i}>{btn(s.map(names).join(' + ')+' won',{type:'potatoResult',side:i})}</span>)}{btn('Ambiguous side — Retry',{type:'retryPotato'})}</>:<p>💣 Timer running. Stay ready.</p>}</>}
 {p.length>0&&['bid','guess','vote','predict','decide'].includes(g.subphase)&&<p>{p.map(id=>names(id)+': '+(g.commits?.[id]?'Locked':'Waiting')).join(' · ')}</p>}
 </>}</div>
}
function BatchLife({ids,names,submit}){const [selected,setSelected]=useState([]);return <details><summary>Simultaneous life losses</summary>{ids.map(id=><label key={id}><input type="checkbox" checked={selected.includes(id)} onChange={e=>setSelected(e.target.checked?[...selected,id]:selected.filter(x=>x!==id))}/>{names(id)}</label>)}<button disabled={!selected.length} onClick={()=>{if(yes('Confirm these life losses happened simultaneously?')){submit(selected);setSelected([])}}}>Record together</button></details>}
function Validity({category}){const [value,setValue]=useState('');const normalized=value.toLowerCase().replace(/[^a-z0-9]/g,'');const valid=(category==='car'?CAR_NAMES:PEOPLE).some(v=>v.toLowerCase().replace(/[^a-z0-9]/g,'')===normalized);return <div><p>Pause the timer before checking. This reference list is not exhaustive; resolve unlisted names verbally.</p><input value={value} onChange={e=>setValue(e.target.value)} placeholder="Disputed name"/>{value&&<p>{valid?'In approved reference list':'Not in reference list — host resolves'}</p>}</div>}

function ParticipantPicker({b,names,host,busy,submit}){
 const size=FORMAT_SIZES[b.format],[slots,setSlots]=useState(()=>[b.challengerId,...b.availableIds.filter(id=>id!==b.challengerId)].slice(0,size));
 const team=b.format==='2v2',asym=['1v2','1v3'].includes(b.format);
 return <section><h3>Choose players{team||asym?' and teams':''}</h3><p>These choices lock before the game is revealed.</p>{Array.from({length:size},(_,i)=><label key={i}>{asym?(i===0?'Solo player':'Team player '+i):team?'Team '+(i<2?1:2)+' player':'Player '+(i+1)}<select disabled={!host||busy} value={slots[i]||''} onChange={e=>setSlots(slots.map((v,j)=>i===j?e.target.value:v))}>{b.availableIds.map(id=><option key={id} value={id}>{names(id)}</option>)}</select></label>)}{host&&<button disabled={busy||new Set(slots).size!==size||!slots.includes(b.challengerId)} onClick={()=>submit(team?[slots.slice(0,2),slots.slice(2)]:asym?[[slots[0]],slots.slice(1)]:slots.map(id=>[id]))}>Lock players & teams</button>}</section>
}
function Scoreboard({g,names}){
 const n=parseInt(g.challengeId.split('-')[1]);
 if(g.engine==='target')return <div className="bc-scoreboard" aria-label="Current points">{g.sides.map((side,i)=><div key={i}><strong>{side.map(names).join(' + ')}</strong><span>{g.scores?.[side[0]]||0} points</span></div>)}</div>;
 if(!['numeric','sprintScore','draft','possession','auction','guess','gauntlet','endurance','sprint','airdribble','series','alphabet','triathlon'].includes(g.engine))return null;
 return <div className="bc-scoreboard" aria-label="Running scores">{g.ids.map(id=>{
 const entries=g.entries?.[id],total=Array.isArray(entries)?entries.reduce((a,b)=>a+b,0):entries;
 let value=g.scores?.[id]||0,label='points';
 if(['numeric','sprintScore'].includes(g.engine)){value=total||0;label=n===65?'goals':'total KPH';if(n===55){value=entries?.length?Math.abs(entries[0]-g.target):'—';label='KPH error'}}
 if(g.engine==='guess'){label=n===30?'total error':'points'}
 if(g.engine==='endurance'){value=entries??'—';label='ending shot'}
 if(g.engine==='airdribble'){value=entries==null?'—':fmt(entries);label='time'}
 if(g.engine==='sprint'){value=entries==null?'—':['1v2','1v3'].includes(g.format)?fmt(entries):'Finished';label=''}
 return <div key={id}><strong>{names(id)}</strong><span>{g.engine==='gauntlet'?'Mechanic splits':value+' '+label}</span>{g.roundWins&&<small>{g.roundWins[id]||0} / 2 round wins</small>}{g.engine==='gauntlet'&&['Easy','Medium','Hard'].map((label,i)=><small key={label}>{label}: {g.laps?.[id]?.[i]==null?'—':fmt(g.laps[id][i]-(g.laps[id][i-1]||0))+' (total '+fmt(g.laps[id][i])+')'}</small>)}</div>
 })}{g.sides?.some(s=>s.length>1)&&['numeric','draft','possession','guess','endurance'].includes(g.engine)&&<p>{g.sides.map((side,i)=>{
 const values=side.map(id=>g.engine==='numeric'?(n===55?Math.abs((g.entries?.[id]?.[0]??g.target)-g.target):(g.entries?.[id]||[]).reduce((a,b)=>a+b,0)):g.engine==='endurance'?Number(g.entries?.[id]||0):g.scores?.[id]||0);
 let total=values.reduce((a,b)=>a+b,0);const asymmetric=['1v2','1v3'].includes(g.format);
 if(g.engine==='numeric'&&n===55&&asymmetric)total/=side.length;
 if(i===0&&asymmetric&&(g.engine==='draft'||g.engine==='numeric'&&[10,26].includes(n)))total*=g.sides[1].length;
 if(g.engine==='numeric'&&[61,62].includes(n)){const entries=g.entries?.[side[0]]||[];total=n===61?Math.max(0,...entries):entries.reduce((a,b)=>a+b,0)}
 return side.map(names).join(' + ')+': '+Math.round(total*100)/100+(g.engine==='numeric'&&n===55?' KPH error':'');
 }).join(' · ')}</p>}</div>
}
function DraftControls({g,uid,names,busy,send}){
 const [counts,setCounts]=useState([0,0,0]),id=g.order[g.turn];
 useEffect(()=>setCounts([0,0,0]),[g.turn,g.attempt,g.round]);
 const mine=uid===id;
 return <section><h3>{names(id)} · {g.draftTimed?'1-minute Rocket League run':'Attempt '+((g.attempt||0)+1)+' / 3'}</h3><p>{g.draftTimed?'Use Rocket League’s clock. Enter every successful mechanic from your run, then finish.':'Select how many of each mechanic you completed within this one shot. A miss earns 0.'}</p>{g.draft.map((m,i)=><label key={i}>{m.name} — {i+1} point{i?'s':''} each<input type="number" min="0" max="100" step="1" disabled={!mine||busy} value={counts[i]} onChange={e=>setCounts(counts.map((v,j)=>j===i?Math.max(0,Math.min(100,Math.floor(Number(e.target.value)||0))):v))}/></label>)}<p>Selected total: {counts.reduce((t,v,i)=>t+v*(i+1),0)}</p>{mine&&<><button disabled={busy} onClick={()=>send({type:g.draftTimed?'finishDraftRun':'draftAttempt',counts,made:true})}>{g.draftTimed?'Finish run':'Submit successful shot'}</button>{!g.draftTimed&&<button disabled={busy} onClick={()=>send({type:'draftAttempt',counts:[0,0,0],made:false})}>Missed shot — 0</button>}</>}</section>
}
function PossessionControls({g,uid,names,busy,now,send}){
 const pressure=g.challengeId==='challenge-25',id=g.possessionOrder[g.possessionIndex],mine=uid===id,extra=g.possessionRound>1,seconds=extra?10:[30,20,10][g.attempt];
 return <section><h3>{names(id)} attacks · Possession {g.attempt+1}/{extra?1:3}</h3><p>{extra?'Tiebreak: one possession each.':'Complete your possessions, then switch attacker.'}</p>{pressure&&<p>{seconds} seconds · Goal worth {extra?3:g.attempt+1} points</p>}{mine&&(pressure&&!g.timer?<button disabled={busy} onClick={()=>send({type:'possessionStart'})}>Start possession</button>:<div>{(pressure?[1,0]:[2,1,0]).map(value=><button key={value} disabled={busy||pressure&&now<g.timer.startedAt} onClick={()=>send({type:'possessionResult',value})}>{pressure?(value?'Goal':'No goal'):value===2?'Goal without bounce — 2':value===1?'Goal with one bounce — 1':'No goal — 0'}</button>)}</div>)}</section>
}

function BattleTurnOrder({g,names}) {
  let ids=g.order.filter(id=>!g.out?.includes(id)), index=g.turn||0
  const turnEngines=['names','bust','draft','airdribble','reverseSpeed','gauntlet','speedladder']
  const sequentialRun=['endurance','sprint'].includes(g.engine)&&['1v2','1v3'].includes(g.format)
  const normalTicTacToe=g.engine==='ttt'&&g.challengeId==='challenge-52'
  if(g.engine==='possession'){ids=g.possessionOrder||[];index=g.possessionIndex||0}
  else if(g.engine==='guess'){ids=g.shooters||g.order;index=g.shot||0}
  else if(g.engine==='auction'){ids=g.bidOrder||[];index=g.bidIndex||0}
  else if(g.engine==='target'){const side=(g.turn||0)%2;ids=g.sides.flat();index=ids.indexOf(g.sides[side]?.[0])}
  else if(!turnEngines.includes(g.engine)&&!sequentialRun&&!normalTicTacToe)return null
  if(!ids.length)return null
  index=((index%ids.length)+ids.length)%ids.length
  return <section className="bc-turn-order" aria-label="Battle turn order"><strong>Turn order</strong><ol>{ids.map((id,i)=><li key={id+'-'+i} className={i===index?'is-current':''} aria-current={i===index?'step':undefined}><span>{i+1}. {names(id)}</span>{i===index&&<b>NOW</b>}{i===(index+1)%ids.length&&ids.length>1&&<small>NEXT</small>}</li>)}</ol></section>
}
